### ISSUE TITLE
Explicitly-loaded channel credentials fail with Language client

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1064]
Code (after installing Google.Cloud.Language.V1 v1.0.0-beta07):

```csharp
using Google.Apis.Auth.OAuth2;
using Google.Cloud.Language.V1;
using Grpc.Auth;
using Grpc.Core;
using System;
using System.IO;

class Program
{
    static void Main(string[] args)
    {
        var cred = LoadCredential(args[0]);

        ChannelCredentials channelCredentials = cred.ToChannelCredentials();
        Channel channel = new Channel(LanguageServiceClient.DefaultEndpoint.ToString(), channelCredentials);
        var client = LanguageServiceClient.Create(channel);
        var response = client.AnalyzeSentiment(Document.FromPlainText("This should work"));
        Console.WriteLine(response);
    }

    static GoogleCredential LoadCredential(string path)
    {
        using (Stream st = File.OpenRead(path))
        {
            return GoogleCredential.FromStream(st);
        }
    }
}
```

Exception:

```text
Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Unauthenticated, Detail="Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
```

I'd expect this to work fine...

**Comment by jskeet** [comment]
@jtattermusch: Any ideas off the top of your head before I investigate more deeply? This looks okay to me...

**Comment by JonKragh** [comment]
Thank you for opening this!

**Comment by jskeet** [comment]
I've got it - the credentials need to have the right scopes.

I *thought* this wasn't an issue any more, but it appears to be at least for Language - I'll investigate internally. But it's easy to work around in client code for now:

```csharp
static GoogleCredential LoadCredential(string path)
{
    using (Stream st = File.OpenRead(path))
    {
        return GoogleCredential.FromStream(st).CreateScoped(LanguageServiceClient.DefaultScopes);
    }
}
```

**Comment by JonKragh** [comment]
Worked like a charm! Thanks brotha!

**Comment by jskeet** [comment]
It's a bug somewhere, but it's not clear where at the moment. Set to P2 as the workaround is reasonably simple.

**Comment by jskeet** [comment]
Closing for now as the issue with scopes isn't likely to be addressed in *this* repo. (Discussion is ongoing though.)
