### ISSUE TITLE
grpc_csharp_ext.x64.dll not found

### ISSUE THREAD

**Issue by Jonathan34** [GoogleCloudPlatform/google-cloud-dotnet#1186]
Hi,

Upgrading `Google.Cloud.Diagnostics.AspNetCore` from  `1.0.0-alpha08` to `1.0.0-beta13`
using `.net core 2.0 preview 1` leads to the following error message

```
 C:\code\test\IntegrationTests\bin\Debug\netcoreapp2.0\grpc
_csharp_ext.x64.dll,C:\code\test\IntegrationTests\bin\Debug\netcoreapp2.0\runtimes/win/native\grpc_csharp_ext.x64.dll,C:\code\test\IntegrationTests\bin
\Debug\netcoreapp2.0\../..\runtimes/win/native\grpc_csharp_ext.x64.dll
Stack Trace:
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.Load()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint, ChannelCredentials credentials)
   at Google.Cloud.Diagnostics.AspNetCore.CloudTraceExtension.AddGoogleTrace(IServiceCollection services, Action`1 setupAction)
   at Startup.ConfigureServices(IServiceCollection services) in C:\code\src\Startup.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at IntegrationTests.TestIHS..ctor() in
```

Environment:
```
$ dotnet --info
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```
Note: it seems to work fine with .net core 1.1. The code that fails is an integration test using the following references:
```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-*" />
    <PackageReference Include="xunit" Version="2.3.0-beta*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta*" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.0.0-preview1-final" />
```

dotnet restore / build / test

**Comment by jskeet** [comment]
Try adding a direct PackageReference to Grpc.Core version 1.4.0. I'm surprised it's not there already - it should be, due to https://github.com/grpc/grpc/issues/11279. I'll add the dependency for the future - thanks for reporting this.

**Comment by jskeet** [comment]
(I've raised #1187 as a more general form of this - if adding the Grpc.Core dependency works, we can close *this* specific bug.)

**Comment by Jonathan34** [comment]
Adding grpc.core worked.
Thanks Jon
