### ISSUE TITLE
Unable to resolve service for type 'Google.Cloud.Diagnostics.Common.IExceptionLogger' while attempting to activate 'Google.Cloud.Diagnostics.AspNetCore.ErrorReportingExceptionLoggerMiddleware'

### ISSUE THREAD

**Issue by Jonathan34** [GoogleCloudPlatform/google-cloud-dotnet#1195]
With exact same environment as https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/1186 

```
dotnet publish 
dotnet project.dll
```

will generate this:

```
Unhandled Exception: System.InvalidOperationException: Unable to resolve service for type 'Google.Cloud.Diagnostics.Common.IExceptionLogger' while attempting to activate 'Google.Cloud.Diagnostics.AspNetCore.ErrorReportingExceptionLoggerMiddleware'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at ihs.Program.BuildWebHost(String[] args) in /Users/jdelfour/code/UCP/UDL-API/ihs/src/Program.cs:line 15
   at ihs.Program.Main(String[] args) in /Users/jdelfour/code/UCP/UDL-API/ihs/src/Program.cs:line 11
Abort trap: 6
```

in the `startup.cs`:

```
void ConfigureServices(IServiceCollection services) {
...
var tracingQPS = Configuration.GetSection("Diagnostics").GetValue<int>("TracingQPS", 1);
        services.AddGoogleTrace(options =>
        {
            options.ProjectId = Configuration["AppSettings:GoogleProjectID"];
            options.TraceFallbackPredicate = TraceDecisionPredicate.Default;
            options.Options = TraceOptions.Create(tracingQPS);
        });

        services.AddMvc();
}
```

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IApplicationLifetime applifetime)
    {
        _logger.LogDebug("Configure() started...");

        //if we are not in prod or dev environments, do local logging to the console (do not send to cloud)
        if (env.IsProduction() || env.IsDevelopment())
        {
            app.UseGoogleExceptionLogging();

            loggerFactory.AddGoogle(Configuration["AppSettings:GoogleProjectID"]);

            app.UseGoogleTrace();
        }
...
}
```
Commenting out `app.UseGoogleExceptionLogging();` fixes the issue

Packages of the project:
```
<ItemGroup>
    <PackageReference Include="Google.Cloud.Diagnostics.AspNetCore" Version="1.0.0-beta*" />
    <PackageReference Include="Google.Cloud.BigQuery.V2" Version="1.0.0-beta*" />
    <PackageReference Include="Slb.Realtime.Witsml.Objects" Version="13.0.200" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview1-final" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0" />
    <PackageReference Include="Microsoft.NETCore.Portable.Compatibility" Version="1.0.1" />
    <PackageReference Include="Google.Apis" Version="1.27.1" />
  <PackageReference Include="Grpc.Core" Version="1.4.0" />
</ItemGroup>
```

`Google.Cloud.Diagnostics.AspNetCore/1.0.0-beta11`
`Google.Cloud.BigQuery.V2/1.0.0-beta13`

**Comment by iantalarico** [comment]
@Jonathan34 It looks like you are missing a dependency on "Google.Cloud.Diagnostics.Common".  Can you try adding it?

@jskeet Shouldn't this be pulled down automatically when the user installs "Google.Cloud.Diagnostics.AspNetCore"?

**Comment by jskeet** [comment]
@iantalarico: Yes, that shouldn't be the problem. I would expect it to be in the ASP.NET Core configuration part. I suggest you try to reproduce and then we can work out what's going on :)

**Comment by iantalarico** [comment]
@Jonathan34, sorry for the delay.  Is there more in your ConfigureServices method?  Do you have the configuration of the exception logging set up?

```
public void ConfigureServices(IServiceCollection services)
...
services.AddGoogleExceptionLogging(options =>
{
  options.ProjectId = "pid";
  options.ServiceName = "service";
  options.Version = "version";
});
...
}
```

**Comment by Jonathan34** [comment]
@iantalarico 
aaaah You are right, I did not have `services.AddGoogleExceptionLogging`.

Funny that i saw that it was required for the tracing but not for the exception logging...

Anyway, seems to work ok now :)

Thanks

**Comment by iantalarico** [comment]
@Jonathan34 Perfect! Glad it's working.
