### ISSUE TITLE
Request contains an invalid argument exception thrown when I think the request is valid.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#1273]
[Code](https://github.com/SurferJeffAtGoogle/csharp-docs-samples/tree/6e37789d43cbc51999d840b7a2c3329e78320121/video/api) looks like this:

```c#
public static object AnalyzeShots(string path)
{
    var client = VideoIntelligenceServiceClient.Create();
    var request = new AnnotateVideoRequest()
    {
        InputContent = Convert.ToBase64String(File.ReadAllBytes(path)),
        Features = { Feature.ShotChangeDetection }
    };
    var op = client.AnnotateVideo(request).PollUntilCompleted();
```

Failed:
```
Test Name:	GoogleCloudSamples.VideoIntelligence.AnalyzeTests.TestShots
Test FullName:	GoogleCloudSamples.VideoIntelligence.AnalyzeTests.TestShots (a98a76b286871b0275d86113fb8e881a41981d0e)
Test Source:	C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\video\api\Test\Tests.cs : line 82
Test Outcome:	Failed
Test Duration:	0:00:13.603

Result StackTrace:	
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.VideoIntelligence.V1Beta1.VideoIntelligenceService.VideoIntelligenceServiceClient.AnnotateVideo(AnnotateVideoRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Cloud.VideoIntelligence.V1Beta1.VideoIntelligenceServiceClientImpl.AnnotateVideo(AnnotateVideoRequest request, CallSettings callSettings)
   at GoogleCloudSamples.VideoIntelligence.Analyzer.AnalyzeShots(String path) in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\video\api\Analyze\Program.cs:line 52
   at GoogleCloudSamples.VideoIntelligence.Analyzer.<>c.<Main>b__6_0(AnalyzeShotsOptions opts) in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\video\api\Analyze\Program.cs:line 191
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 notParsedFunc)
   at GoogleCloudSamples.VideoIntelligence.Analyzer.Main(String[] args) in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\video\api\Analyze\Program.cs:line 186
   at GoogleCloudSamples.CommandLineRunner.Run(String[] arguments) in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\testutil\TestUtil.cs:line 132
   at GoogleCloudSamples.VideoIntelligence.AnalyzeTests.TestShots() in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\video\api\Test\Tests.cs:line 84
Result Message:	Grpc.Core.RpcException : Status(StatusCode=InvalidArgument, Detail="Request contains an invalid argument.")
```

**Comment by jskeet** [comment]
I had this when I was trying to use a whitelisted feature without being in the whitelist.

**Comment by SurferJeffAtGoogle** [comment]
Is there a bug upstream asking for a clearer error message?

**Comment by jskeet** [comment]
Yes, although I can't check now. (Find bugs reported by me...)

**Comment by SurferJeffAtGoogle** [comment]
Actually, I don't think this issue has anything to do with whitelisting.  When I run the PHP sample that calls the same API with the same credentials and same project, the PHP code succeeds.

**Comment by SurferJeffAtGoogle** [comment]
Scratch that.
