### ISSUE TITLE
There was a conflict between "Google.Api.Gax, Version=2.0.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47" and "Google.Api.Gax, Version=2.1.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953 e47".

### ISSUE THREAD

**Issue by Jonathan34** [GoogleCloudPlatform/google-cloud-dotnet#1280]
Hi,

Using .net core 1.1.2 (sdk 1.0.4) on windows.
```
using the reference
    <TargetFramework>netcoreapp1.1</TargetFramework>
...
    <PackageReference Include="Google.Cloud.Diagnostics.AspNetCore" Version="1.0.0-beta12" />
```

then using 
```
services.AddGoogleTrace(options =>
        {
            options.ProjectId = Configuration["AppSettings:GoogleProjectID"];
            options.TraceFallbackPredicate = TraceDecisionPredicate.Default;
            options.Options = TraceOptions.Create(tracingQPS);
        });

        services.AddGoogleExceptionLogging(options =>
        {
            options.ProjectId = Configuration["AppSettings:GoogleProjectID"];
            options.ServiceName = "ServiceName";
            options.Version = "1.0";
        });

```

generates the following warnings:
```
There was a conflict between "Google.Api.Gax, Version=2.0.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47" and "Google.Api.Gax, Version=2.1.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953
e47".
             "Google.Api.Gax, Version=2.0.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47" was chosen because it was primary and "Google.Api.Gax, Version=2.1.0.0, Culture=neutral, PublicKeyToken=3ec5
ea7f18953e47" was not.
             References which depend on "Google.Api.Gax, Version=2.0.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47" [C:\Users\Jon\.nuget\packages\google.api.gax\2.0.0\lib\netstandard1.3\Google
.Api.Gax.dll].
                 C:\Users\Jon\.nuget\packages\google.api.gax\2.0.0\lib\netstandard1.3\Google.Api.Gax.dll
                   Project file item includes which caused reference "C:\Users\Jon\.nuget\packages\google.api.gax\2.0.0\lib\netstandard1.3\Google.Api.Gax.dll".
                     C:\Users\Jon\.nuget\packages\google.api.gax\2.0.0\lib\netstandard1.3\Google.Api.Gax.dll
             References which depend on "Google.Api.Gax, Version=2.1.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47" [].
                 C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.aspnetcore\1.0.0-beta12\lib\netstandard1.5\Google.Cloud.Diagnostics.AspNetCore.dll
                   Project file item includes which caused reference "C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.aspnetcore\1.0.0-beta12\lib\netstandard1.5\Google.Cloud.Diagnostics.AspNetCo
re.dll".
                     C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.aspnetcore\1.0.0-beta12\lib\netstandard1.5\Google.Cloud.Diagnostics.AspNetCore.dll
                 C:\Users\Jon\.nuget\packages\google.cloud.logging.v2\2.0.0\lib\netstandard1.5\Google.Cloud.Logging.V2.dll
                   Project file item includes which caused reference "C:\Users\Jon\.nuget\packages\google.cloud.logging.v2\2.0.0\lib\netstandard1.5\Google.Cloud.Logging.V2.dll".
                     C:\Users\Jon\.nuget\packages\google.cloud.logging.v2\2.0.0\lib\netstandard1.5\Google.Cloud.Logging.V2.dll
                     C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.aspnetcore\1.0.0-beta12\lib\netstandard1.5\Google.Cloud.Diagnostics.AspNetCore.dll
                     C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.common\1.0.0-beta04\lib\netstandard1.5\Google.Cloud.Diagnostics.Common.dll
                 C:\Users\Jon\.nuget\packages\google.api.gax.grpc\2.0.0\lib\netstandard1.5\Google.Api.Gax.Grpc.dll
                   Project file item includes which caused reference "C:\Users\Jon\.nuget\packages\google.api.gax.grpc\2.0.0\lib\netstandard1.5\Google.Api.Gax.Grpc.dll".
                     C:\Users\Jon\.nuget\packages\google.api.gax.grpc\2.0.0\lib\netstandard1.5\Google.Api.Gax.Grpc.dll
                 C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.common\1.0.0-beta04\lib\netstandard1.5\Google.Cloud.Diagnostics.Common.dll
                   Project file item includes which caused reference "C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.common\1.0.0-beta04\lib\netstandard1.5\Google.Cloud.Diagnostics.Common.dll".

                     C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.aspnetcore\1.0.0-beta12\lib\netstandard1.5\Google.Cloud.Diagnostics.AspNetCore.dll
                     C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.common\1.0.0-beta04\lib\netstandard1.5\Google.Cloud.Diagnostics.Common.dll
                 C:\Users\Jon\.nuget\packages\google.cloud.trace.v1\1.0.0-beta07\lib\netstandard1.5\Google.Cloud.Trace.V1.dll
                   Project file item includes which caused reference "C:\Users\Jon\.nuget\packages\google.cloud.trace.v1\1.0.0-beta07\lib\netstandard1.5\Google.Cloud.Trace.V1.dll".
                     C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.aspnetcore\1.0.0-beta12\lib\netstandard1.5\Google.Cloud.Diagnostics.AspNetCore.dll
                     C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.common\1.0.0-beta04\lib\netstandard1.5\Google.Cloud.Diagnostics.Common.dll
                     C:\Users\Jon\.nuget\packages\google.cloud.trace.v1\1.0.0-beta07\lib\netstandard1.5\Google.Cloud.Trace.V1.dll
         There was a conflict between "Google.Api.Gax.Grpc, Version=2.0.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47" and "Google.Api.Gax.Grpc, Version=2.1.0.0, Culture=neutral, PublicKeyToken=3ec
5ea7f18953e47".
             "Google.Api.Gax.Grpc, Version=2.0.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47" was chosen because it was primary and "Google.Api.Gax.Grpc, Version=2.1.0.0, Culture=neutral, PublicKey
Token=3ec5ea7f18953e47" was not.
             References which depend on "Google.Api.Gax.Grpc, Version=2.0.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47" [C:\Users\Jon\.nuget\packages\google.api.gax.grpc\2.0.0\lib\netstandard
1.5\Google.Api.Gax.Grpc.dll].
                 C:\Users\Jon\.nuget\packages\google.api.gax.grpc\2.0.0\lib\netstandard1.5\Google.Api.Gax.Grpc.dll
                   Project file item includes which caused reference "C:\Users\Jon\.nuget\packages\google.api.gax.grpc\2.0.0\lib\netstandard1.5\Google.Api.Gax.Grpc.dll".
                     C:\Users\Jon\.nuget\packages\google.api.gax.grpc\2.0.0\lib\netstandard1.5\Google.Api.Gax.Grpc.dll
             References which depend on "Google.Api.Gax.Grpc, Version=2.1.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47" [].
                 C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.aspnetcore\1.0.0-beta12\lib\netstandard1.5\Google.Cloud.Diagnostics.AspNetCore.dll
                   Project file item includes which caused reference "C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.aspnetcore\1.0.0-beta12\lib\netstandard1.5\Google.Cloud.Diagnostics.AspNetCo
re.dll".
                     C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.aspnetcore\1.0.0-beta12\lib\netstandard1.5\Google.Cloud.Diagnostics.AspNetCore.dll
                 C:\Users\Jon\.nuget\packages\google.cloud.trace.v1\1.0.0-beta07\lib\netstandard1.5\Google.Cloud.Trace.V1.dll
                   Project file item includes which caused reference "C:\Users\Jon\.nuget\packages\google.cloud.trace.v1\1.0.0-beta07\lib\netstandard1.5\Google.Cloud.Trace.V1.dll".
                     C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.aspnetcore\1.0.0-beta12\lib\netstandard1.5\Google.Cloud.Diagnostics.AspNetCore.dll
                     C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.common\1.0.0-beta04\lib\netstandard1.5\Google.Cloud.Diagnostics.Common.dll
                     C:\Users\Jon\.nuget\packages\google.cloud.trace.v1\1.0.0-beta07\lib\netstandard1.5\Google.Cloud.Trace.V1.dll
                 C:\Users\Jon\.nuget\packages\google.cloud.logging.v2\2.0.0\lib\netstandard1.5\Google.Cloud.Logging.V2.dll
                   Project file item includes which caused reference "C:\Users\Jon\.nuget\packages\google.cloud.logging.v2\2.0.0\lib\netstandard1.5\Google.Cloud.Logging.V2.dll".
                     C:\Users\Jon\.nuget\packages\google.cloud.logging.v2\2.0.0\lib\netstandard1.5\Google.Cloud.Logging.V2.dll
                     C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.aspnetcore\1.0.0-beta12\lib\netstandard1.5\Google.Cloud.Diagnostics.AspNetCore.dll
                     C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.common\1.0.0-beta04\lib\netstandard1.5\Google.Cloud.Diagnostics.Common.dll
                 C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.common\1.0.0-beta04\lib\netstandard1.5\Google.Cloud.Diagnostics.Common.dll
                   Project file item includes which caused reference "C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.common\1.0.0-beta04\lib\netstandard1.5\Google.Cloud.Diagnostics.Common.dll".

                     C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.aspnetcore\1.0.0-beta12\lib\netstandard1.5\Google.Cloud.Diagnostics.AspNetCore.dll
                     C:\Users\Jon\.nuget\packages\google.cloud.diagnostics.common\1.0.0-beta04\lib\netstandard1.5\Google.Cloud.Diagnostics.Common.dll
     1>C:\Program Files\dotnet\sdk\1.0.4\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolv
ed.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\code\UDL\UDL-API\Gateway\src\UDL-API.csproj]
```

Ultimately, this prevents a deployment to gcloud using the aspnetcore1.1 image

```
2017-07-26T14:29:23.8186990Z Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Google.Api.Gax, Version=2.1.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
2017-07-26T14:29:23.8230890Z    at Google.Cloud.Diagnostics.AspNetCore.CloudTraceExtension.AddGoogleTrace(IServiceCollection services, Action`1 setupAction)
2017-07-26T14:29:23.8243030Z    at Startup.ConfigureServices(IServiceCollection services) in /app/Gateway/src/Startup.cs:line 103
2017-07-26T14:29:23.8284060Z --- End of stack trace from previous location where exception was thrown ---
2017-07-26T14:29:23.8323420Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-07-26T14:29:23.8334830Z    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
2017-07-26T14:29:23.8348330Z    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
2017-07-26T14:29:23.8359710Z    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
2017-07-26T14:29:23.8370720Z    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
2017-07-26T14:29:23.8381830Z    at ConsoleApplication.Program.Main(String[] args) in /app/Gateway/src/Program.cs:line 12
```

using the package `Google.Cloud.Diagnostics.AspNetCore" Version="1.0.0-beta12"` works fine

**Comment by iantalarico** [comment]
@Jonathan34 You say "using the package Google.Cloud.Diagnostics.AspNetCore" Version="1.0.0-beta12" works fine" Do you mean using the package by itself works fine? without deploying?

**Comment by Jonathan34** [comment]
I mean I have this package as a nuget PackageReference in my project.csproj.
Same issue appears in a .net core 2.0 preview 2 project.

I tried adding a reference to `gax v2.1.0-beta*` but that does not work .

**Comment by jskeet** [comment]
It's not clear to me what you mean when you say

> using the package Google.Cloud.Diagnostics.AspNetCore" Version="1.0.0-beta12" works fine

... when you *also* show that using that package, it doesn't work fine. If you mean it works fine in one situation but not another, please supply more details.

When you say that adding a reference to 2.1.0-beta01 "does not work" - what happens? Can you provide an absolutely minimal project file and any code required to reproduce the problem? (Given that it happens at build time, I'd expect just a very simple console app to do it...)

**Comment by Jonathan34** [comment]
beta11 works fine, sorry!
If i add a hardcoded reference i still get the same conflict issue

**Comment by Jonathan34** [comment]
[testapp.zip](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/files/1177398/testapp.zip)

her eyou go, you can ignore the test folder

**Comment by jskeet** [comment]
I'm on vacation at the moment but will have a go at reproducing. I'd expect anything requiring 2.0.0 to be fine with 2.1.0-beta01...

**Comment by iantalarico** [comment]
Thanks, I'll give this code a try.

@jskeet  Looking at some of the dependencies it looks like Google.Cloud.Logging.V2 is using Google.Api.Gax.Grpc 2.1.0-beta01 and Google.Cloud.Trace.V1 is using Google.Api.Gax.Grpc 2.0.0.

**Comment by Jonathan34** [comment]
Np, I hard-coded the version to beta 11 for the time being.
enjoy your vacation :)

**Comment by jskeet** [comment]
@iantalarico: Yup, I'm sure that's it, but I wouldn't expect it to cause a problem.

**Comment by iantalarico** [comment]
I've been able to repo the issue with the given repo and am looking more into it.

**Comment by iantalarico** [comment]
It looks like if we downgrade to Google.Api.Gax 2.0.0 (which we will need to do for Trace before we GA) and add explicit dependencies to Google.Api.Gax 2.0.0 in the Trace and Logging projects this fixes it.

@jskeet This seems wrong to me but I'm not seeing a better path.

@benwulfe Did you do something similar for Datastore?  Did that cause any issues?

**Comment by jskeet** [comment]
@iantalarico: I really want to understand this better before doing anything else. I can't see any reason why we *shouldn't* be able to use GAX 2.1.0-beta01 to satisfy a 2.0.0 dependency. Do you have an absolutely minimal example yet? (If not, I'll look at creating one next week.)

Basically, we need to understand versioning as thoroughly as we can. We *will* get situations like this in the future, where not every version of every library depends on exactly the same set of minor versions. We need to make that work.

**Comment by benwulfe** [comment]
I believe I do have an explicit dependency on grpc.core.

Without a binding redirect, referencing multiple versions will attempt to
load multiple assemblies SxS, right Jon?

Possibly nuget might be fixing this up as long as the dependencies are
explicit -- but if an assembly has an indirect reference to an older
version, I cannot see how this would be fixed.

I also seem to recall that build and revision numbers are not included in
assembly  binding, but major + minor are -- but it's been a while (version
numbers are major.minor.build.revision).
I do know that back in the day, testing Side x Side loads (loading multiple
versions of an assembly into an appdomain) was a 'thing' as this is classic
.net versioning that was an attempt to fix dll hell.

-ben

**Comment by jskeet** [comment]
I believe that .NET Core has different ways of sorting this out than desktop .NET, but I need to look into it more deeply. This is the kind of thing I want to become more expert at anyway, tbh.

**Comment by iantalarico** [comment]
@jskeet Any pointers for books on this? This is something I need to understand better.

**Comment by jskeet** [comment]
Not yet. I'm going to start digging in on Monday, and will try to write up what I find as I go.

**Comment by benwulfe** [comment]
This is pretty confusing because if I built I portable library, there are
cases it would run on the desktop clr with its versioning semantics and
cases where it would load on .net core with semver.

how very odd this is...

**Comment by jskeet** [comment]
It's not a matter of the versioning *semantics*, but the *mechanisms*. I don't think SemVer is built into the CLR (in either Core or Desktop) - it's more a convention for everyone to follow than anything else.

**Comment by benwulfe** [comment]
Right -- but there is a very explicit loading *mechanism *(fusion) built
into the desktop clr and I'd be surprised if it worked any differently in
other .net runtimes.

So far in my cursory google-fu, it looks like nuget implements its
versioning/dependency semantics on top of fusion via binding redirects.
But I'm not yet at the point at seeing how it decides which redirects to
add -- but it seems loosely based on the nuget package dependency
declaration along with scanning assembly manifests.

So my (hand wave) guess is that this sort of error will come up if we
forget to explicitly declare a dependency in one of our nuget packages.  eg
- if the user manually has to install a dependency to get things to work,
then nuget may not think it needs to fix up the dependencies in that case
with redirects.

So Ian -- maybe a simple check here is to ensure that each of the used
packages in the repro project work in a standalone app without having to
manually add a dependency.

**Comment by iantalarico** [comment]
@Jonathan34 We have released a new version for Google.Cloud.Diagnostics.AspNetCore "1.0.0-beta13" it was tested with your sample and worked.  Please let us know if this doesn't work for you.

@jskeet Ben (@benwulfe) and I managed to figure out that this was due to project dependencies (trace and logging) in Google.Cloud.Diagnostcs.Common.  We changed these to package dependencies instead.  Ben set aside some time next week for us to chat and make sure we end up with the best long term solution.

**Comment by Jonathan34** [comment]
works fine! thanks

**Comment by jskeet** [comment]
Aha. I now understand too. Logging shouldn't have caused a problem, but Trace would have done. Will think about possible solutions before our meeting.
