### ISSUE TITLE
ErrorReportingExceptionLoggerMiddleware can swallow Exceptions

### ISSUE THREAD

**Issue by carusology** [GoogleCloudPlatform/google-cloud-dotnet#1350]
For a few minutes today, our ASP.NET Core Web API was returning unexpected 500 exceptions.

While we normally see these errors via StackDriver's ErrorReporting module, today we were told by our colleagues, and after we were informed we did not see any errors get added to the StackDriver ErrorReporting module. When we investigated the logs of the web servers directly, we could not glean any additional information because the ErrorReporting middleware appeared to be throwing its own exceptions on how it was failing to report failures to StackDriver, which appears to swallow the original exception it was trying to report in the first place.

Here's the stack trace I found in the logs:

```
      Request finished in 35825.8552ms 500 
  [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
     at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  --- End of stack trace from previous location where exception was thrown ---
     at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  --- End of stack trace from previous location where exception was thrown ---
     at Google.Cloud.Diagnostics.AspNetCore.ErrorReportingExceptionLoggerMiddleware.<Invoke>d__3.MoveNext()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  --- End of stack trace from previous location where exception was thrown ---
     at Google.Cloud.Diagnostics.Common.GrpcErrorEventConsumer.<ReceiveAsync>d__4.MoveNext()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  --- End of stack trace from previous location where exception was thrown ---
     at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  Grpc.Core.RpcException: Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")
```

My first instinct from reading through the source is that [this line](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/ab44b24aa869c880ff7c834588b4f085f0850f29/apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/ErrorReporting/ErrorReportingExceptionLoggerMiddleware.cs#L57) should have a try/catch of its own and, if it were to fail, the original Exception and this new Exception that was raised during logging should be combined into an [`AggregateException`](https://msdn.microsoft.com/en-us/library/system.aggregateexception(v=vs.110).aspx), and the aggregate should be thrown. If the logging succeeds, the original exception can be rethrown via a naked `throw;` as its does today.

Thoughts?

**Comment by iantalarico** [comment]
@carusology, I think that may be the correct thing to do here.  Let me think on this a little more and I will report back soon.

**Comment by iantalarico** [comment]
Leaving open until I push a new release.  I will try and push one out today.

**Comment by carusology** [comment]
I'm impressed. Thanks, @iantalarico.

**Comment by iantalarico** [comment]
@carusology Thank you for the detailed feedback! It's much appreciated.  

I just pushed Google.Cloud.Diagnostics.AspNetCore 1.0.0-beta15.  Please let me know if you have other feedback, comments or suggestions.  Thanks!
