### ISSUE TITLE
Pubsub SimplePublisher throws exception.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#1390]
```
PS C:\Users\rennie\gitrepos\dotnet-docs-samples\pubsub\api\bin\Debug> .\Pubsub.exe listProjectTopics $env:GOOGLE_PROJECT
_ID

Unhandled Exception: System.MissingMethodException: The native method "grpcsharp_completion_queue_create_async" does not
 exist
   at Grpc.Core.Internal.UnmanagedLibrary.GetNativeMethodDelegate[T](String methodName)
   at Grpc.Core.Internal.NativeMethods.GetMethodDelegate[T](UnmanagedLibrary library)
   at Grpc.Core.Internal.NativeMethods..ctor(UnmanagedLibrary library)
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Grpc.Core.Channel..ctor(String host, Int32 port, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint, ChannelCredentials credentials)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint)
   at Google.Cloud.PubSub.V1.PublisherClient.Create(ServiceEndpoint endpoint, PublisherSettings settings)
   at GoogleCloudSamples.Program.ListProjectTopics(String projectId) in C:\Users\rennie\gitrepos\dotnet-docs-samples\pub
sub\api\Program.cs:line 399
   at GoogleCloudSamples.Program.<>c.<Main>b__15_10(ListProjectTopicsOptions opts) in C:\Users\rennie\gitrepos\dotnet-do
cs-samples\pubsub\api\Program.cs:line 481
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,TResult](ParserResult`
1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 par
sedFunc6, Func`2 parsedFunc7, Func`2 parsedFunc8, Func`2 parsedFunc9, Func`2 parsedFunc10, Func`2 parsedFunc11, Func`2 p
arsedFunc12, Func`2 parsedFunc13, Func`2 parsedFunc14, Func`2 notParsedFunc)
   at GoogleCloudSamples.Program.Main(String[] args) in C:\Users\rennie\gitrepos\dotnet-docs-samples\pubsub\api\Program.
cs:line 453
```

Using latest nuget packages:
```
Id                                  Versions                                 ProjectName                                                                                                                                                                                      
--                                  --------                                 -----------                                                                                                                                                                                      
CommandLineParser                   {2.1.1-beta}                             Pubsub                                                                                                                                                                                           
Google.Api.CommonProtos             {1.1.0}                                  Pubsub                                                                                                                                                                                           
Google.Api.Gax                      {2.1.0-beta02}                           Pubsub                                                                                                                                                                                           
Google.Api.Gax.Grpc                 {2.1.0-beta02}                           Pubsub                                                                                                                                                                                           
Google.Apis                         {1.28.0}                                 Pubsub                                                                                                                                                                                           
Google.Apis.Auth                    {1.28.0}                                 Pubsub                                                                                                                                                                                           
Google.Apis.Core                    {1.28.0}                                 Pubsub                                                                                                                                                                                           
Google.Cloud.Iam.V1                 {1.0.0-beta12}                           Pubsub                                                                                                                                                                                           
Google.Cloud.PubSub.V1              {1.0.0-beta13}                           Pubsub                                                                                                                                                                                           
Google.Protobuf                     {3.3.0}                                  Pubsub                                                                                                                                                                                           
Grpc.Auth                           {1.4.0}                                  Pubsub                                                                                                                                                                                           
Grpc.Core                           {1.4.0}                                  Pubsub                                                                                                                                                                                           
log4net                             {2.0.3}                                  Pubsub                                                                                                                                                                                           
Newtonsoft.Json                     {10.0.2}                                 Pubsub                                                                                                                                                                                           
System.Interactive.Async            {3.1.1}                                  Pubsub                                                                                                                                                                                           
System.Net.Http                     {4.3.1}                                  Pubsub                                                                                                                                                                                           
Zlib.Portable.Signed                {1.11.0}                                 Pubsub                       
```

Code is here:
https://github.com/SurferJeffAtGoogle/csharp-docs-samples/blob/04b757fd5e9951d4467fdb72f427d0db2a3594b2/pubsub/api/Program.cs

**Comment by jskeet** [comment]
I can't reproduce - it works fine for me. Do you have another copy of grpc_csharp_ext.x64.dll on the path somewhere, perhaps? How were you running this?

**Comment by SurferJeffAtGoogle** [comment]
Hmmmm.  Not happening on my other machine....  More to come.
