### ISSUE TITLE
Video API somehow blows out memory.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#1655]
Somehow, the video API runs out of memory.
The code lives here:
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/video/api
I see nothing in the code or tests that would cause it to run out of memory.

```
./video/api/Test/runTests.ps1
Set timeout to 900 seconds.
  Restoring packages for /tmpfs/src/github/dotnet-docs-samples/video/api/Analyze/Analyze.csproj...
  Restoring packages for /tmpfs/src/github/dotnet-docs-samples/testutil/testutil.csproj...
  Restoring packages for /tmpfs/src/github/dotnet-docs-samples/commandlineutil/Lib/CommandLineUtil.csproj...
  Restoring packages for /tmpfs/src/github/dotnet-docs-samples/video/api/QuickStart/QuickStart.csproj...
  Installing System.Threading 4.0.11-rc2-24027.
  Installing System.Reflection.Emit.ILGeneration 4.0.1-rc2-24027.
  Installing System.ObjectModel 4.0.12-rc2-24027.
  Installing System.Reflection.Emit 4.0.1-rc2-24027.
  Installing System.Reflection.Emit.Lightweight 4.0.1-rc2-24027.
  Installing System.Threading.Tasks 4.0.11-rc2-24027.
  Installing System.Text.Encoding 4.0.11-rc2-24027.
  Installing System.Reflection.Primitives 4.0.1-rc2-24027.
  Installing System.Linq.Expressions 4.0.11-rc2-24027.
  Installing System.IO 4.1.0-rc2-24027.
  Installing System.Console 4.0.0-rc2-24027.
  Installing System.Reflection 4.1.0-rc2-24027.
  Installing System.Linq 4.1.0-rc2-24027.
  Installing System.Collections 4.0.11-rc2-24027.
  Installing System.Resources.ResourceManager 4.0.1-rc2-24027.
  Installing System.Runtime 4.1.0-rc2-24027.
  Installing System.Globalization 4.0.11-rc2-24027.
  Installing CommandLineParser 2.1.1-beta.
  Installing System.Reflection.Extensions 4.0.1-rc2-24027.
  Installing System.Diagnostics.Debug 4.0.11-rc2-24027.
  Installing System.Reflection.TypeExtensions 4.1.0-rc2-24027.
  Installing System.Runtime.Extensions 4.1.0-rc2-24027.
  Installing Microsoft.Win32.Registry 4.3.0.
  Installing System.Net.WebHeaderCollection 4.3.0.
  Installing System.Net.Http 4.3.1.
  Installing System.Diagnostics.Process 4.3.0.
  Installing System.Net.Requests 4.3.0.
  Installing Google.Apis.Core 1.27.1.
  Installing Newtonsoft.Json 10.0.2.
  Installing xunit.abstractions 2.0.1.
  Installing Google.Apis 1.27.1.
  Installing Google.Apis.Auth 1.27.1.
  Installing Google.Api.Gax 2.0.0.
  Installing xunit.extensibility.core 2.2.0.
  Installing xunit.extensibility.execution 2.2.0.
  Installing Google.Apis.Storage.v1 1.27.1.881.
  Installing Google.Api.Gax.Rest 2.0.0.
  Installing xunit.core 2.2.0.
  Installing xunit 2.2.0.
  Installing Google.Cloud.Storage.V1 2.0.0.
  Installing xunit.assert 2.2.0.
  Installing Google.Apis.Core 1.29.1.
  Installing Google.Apis 1.29.1.
  Installing Google.Protobuf 3.3.0.
  Installing Google.Apis.Auth 1.29.1.
  Installing Google.Api.Gax 2.1.0.
  Installing Google.Api.CommonProtos 1.1.0.
  Installing Grpc.Auth 1.6.1.
  Installing Google.Protobuf 3.4.1.
  Installing Google.Api.Gax.Grpc 2.1.0.
  Installing Google.LongRunning 1.0.0.
  Installing Grpc.Core 1.6.1.
  Installing Google.Cloud.VideoIntelligence.V1Beta2 1.0.0-beta02.
  Generating MSBuild file /tmpfs/src/github/dotnet-docs-samples/commandlineutil/Lib/obj/CommandLineUtil.csproj.nuget.g.props.
  Generating MSBuild file /tmpfs/src/github/dotnet-docs-samples/commandlineutil/Lib/obj/CommandLineUtil.csproj.nuget.g.targets.
  Restore completed in 3.04 sec for /tmpfs/src/github/dotnet-docs-samples/commandlineutil/Lib/CommandLineUtil.csproj.
  Restoring packages for /tmpfs/src/github/dotnet-docs-samples/video/api/Test/Test.csproj...
  Generating MSBuild file /tmpfs/src/github/dotnet-docs-samples/testutil/obj/testutil.csproj.nuget.g.props.
  Generating MSBuild file /tmpfs/src/github/dotnet-docs-samples/testutil/obj/testutil.csproj.nuget.g.targets.
  Restore completed in 3.81 sec for /tmpfs/src/github/dotnet-docs-samples/testutil/testutil.csproj.
  Generating MSBuild file /tmpfs/src/github/dotnet-docs-samples/video/api/Analyze/obj/Analyze.csproj.nuget.g.props.
  Generating MSBuild file /tmpfs/src/github/dotnet-docs-samples/video/api/Analyze/obj/Analyze.csproj.nuget.g.targets.
  Restore completed in 3.94 sec for /tmpfs/src/github/dotnet-docs-samples/video/api/Analyze/Analyze.csproj.
  Generating MSBuild file /tmpfs/src/github/dotnet-docs-samples/video/api/QuickStart/obj/QuickStart.csproj.nuget.g.props.
  Generating MSBuild file /tmpfs/src/github/dotnet-docs-samples/video/api/QuickStart/obj/QuickStart.csproj.nuget.g.targets.
  Restore completed in 3.85 sec for /tmpfs/src/github/dotnet-docs-samples/video/api/QuickStart/QuickStart.csproj.
  Installing System.Xml.XmlSerializer 4.3.0.
  Installing System.Private.DataContractSerialization 4.3.0.
  Installing System.Runtime.Serialization.Json 4.3.0.
  Installing System.ComponentModel.EventBasedAsync 4.3.0.
  Installing System.Diagnostics.TextWriterTraceListener 4.3.0.
  Installing System.Diagnostics.TraceSource 4.3.0.
  Installing System.Runtime.Loader 4.3.0.
  Installing Microsoft.DotNet.PlatformAbstractions 1.0.3.
  Installing Microsoft.TestPlatform.ObjectModel 15.3.0.
  Installing Microsoft.Extensions.DependencyModel 1.0.3.
  Installing xunit.extensibility.execution 2.3.0.
  Installing xunit.extensibility.core 2.3.0.
  Installing Microsoft.TestPlatform.TestHost 15.3.0.
  Installing Microsoft.DotNet.InternalAbstractions 1.0.0.
  Installing Microsoft.Extensions.DependencyModel 1.0.0.
  Installing xunit.analyzers 0.7.0.
  Installing xunit 2.3.0.
  Installing xunit.runner.visualstudio 2.3.0.
  Installing Microsoft.NET.Test.Sdk 15.3.0.
  Installing xunit.assert 2.3.0.
  Installing xunit.core 2.3.0.
  Generating MSBuild file /tmpfs/src/github/dotnet-docs-samples/video/api/Test/obj/Test.csproj.nuget.g.props.
  Generating MSBuild file /tmpfs/src/github/dotnet-docs-samples/video/api/Test/obj/Test.csproj.nuget.g.targets.
  Restore completed in 3.53 sec for /tmpfs/src/github/dotnet-docs-samples/video/api/Test/Test.csproj.
Build started, please wait...
Build completed.

Test run for /tmpfs/src/github/dotnet-docs-samples/video/api/Test/bin/Debug/netcoreapp2.0/Test.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.9170026]   Discovering: Test
[xUnit.net 00:00:01.0300281]   Discovered:  Test
[xUnit.net 00:00:01.0384428]   Starting:    Test
QuickStart 
Analyze labels /tmp/tmpX87iFG.tmp
Analyze explicit-content gs://demomaker/gbike.mp4
Analyze 
[xUnit.net 00:06:23.2221130]     
GoogleCloudSamples.VideoIntelligence.AnalyzeTests.TestAnalyzeNoArgsSucceeds 
[FAIL]
Analyze shots gs://cloudmleap/video/next/fox-snatched.mp4
[xUnit.net 00:06:23.2234073]       System.OutOfMemoryException : Insufficient memory to continue the execution of the program.
[xUnit.net 00:06:23.2244942]       Stack Trace:
[xUnit.net 00:06:23.2255982]            at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
[xUnit.net 00:06:23.2256835]            at System.Text.StringBuilder.Append(Char* value, Int32 valueCount)
[xUnit.net 00:06:23.2257553]            at System.Text.StringBuilder.AppendHelper(String value)
[xUnit.net 00:06:23.2257991]            at System.Text.StringBuilder.Append(String value)
[xUnit.net 00:06:23.2258432]            at CommandLine.Text.HelpText.AddLine(StringBuilder builder, String value, Int32 maximumLength)
[xUnit.net 00:06:23.2258848]            at CommandLine.Text.HelpText.DefaultParsingErrorsHandler[T](ParserResult`1 parserResult, HelpText current)
[xUnit.net 00:06:23.2259240]            at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult, Func`2 onError, Func`2 onExample, Boolean verbsIndex, Int32 maxDisplayWidth)
[xUnit.net 00:06:23.2259584]            at CommandLine.Parser.<>c__DisplayClass17_0`1.<DisplayHelp>b__1(IEnumerable`1 _, TextWriter writer)
[xUnit.net 00:06:23.2259802]            at CSharpx.MaybeExtensions.Do[T1,T2](Maybe`1 maybe, Action`2 action)
[xUnit.net 00:06:23.2260045]            at CommandLine.ParserResultExtensions.WithNotParsed[T](ParserResult`1 result, Action`1 action)
[xUnit.net 00:06:23.2260282]            at CommandLine.Parser.DisplayHelp[T](ParserResult`1 parserResult, TextWriter helpWriter, Int32 maxDisplayWidth)
[xUnit.net 00:06:23.2260671]         /tmpfs/src/github/dotnet-docs-samples/commandlineutil/Lib/VerbMap.cs(85,0): at GoogleCloudSamples.VerbMap`1.Run(String[] args, Parser parser)
[xUnit.net 00:06:23.2261051]         /tmpfs/src/github/dotnet-docs-samples/video/api/Analyze/Program.cs(171,0): at GoogleCloudSamples.VideoIntelligence.Analyzer.Main(String[] args)
[xUnit.net 00:06:23.2261385]         /tmpfs/src/github/dotnet-docs-samples/testutil/TestUtil.cs(136,0): at GoogleCloudSamples.CommandLineRunner.Run(String[] arguments)
[xUnit.net 00:06:23.2261697]         /tmpfs/src/github/dotnet-docs-samples/video/api/Test/Tests.cs(50,0): at GoogleCloudSamples.VideoIntelligence.AnalyzeTests.TestAnalyzeNoArgsSucceeds()
Failed   GoogleCloudSamples.VideoIntelligence.AnalyzeTests.TestAnalyzeNoArgsSucceeds
Error Message:
 System.OutOfMemoryException : Insufficient memory to continue the execution of the program.
Stack Trace:
   at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
   at System.Text.StringBuilder.Append(Char* value, Int32 valueCount)
   at System.Text.StringBuilder.AppendHelper(String value)
   at System.Text.StringBuilder.Append(String value)
   at CommandLine.Text.HelpText.AddLine(StringBuilder builder, String value, Int32 maximumLength)
   at CommandLine.Text.HelpText.DefaultParsingErrorsHandler[T](ParserResult`1 parserResult, HelpText current)
   at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult, Func`2 onError, Func`2 onExample, Boolean verbsIndex, Int32 maxDisplayWidth)
   at CommandLine.Parser.<>c__DisplayClass17_0`1.<DisplayHelp>b__1(IEnumerable`1 _, TextWriter writer)
   at CSharpx.MaybeExtensions.Do[T1,T2](Maybe`1 maybe, Action`2 action)
   at CommandLine.ParserResultExtensions.WithNotParsed[T](ParserResult`1 result, Action`1 action)
   at CommandLine.Parser.DisplayHelp[T](ParserResult`1 parserResult, TextWriter helpWriter, Int32 maxDisplayWidth)
   at GoogleCloudSamples.VerbMap`1.Run(String[] args, Parser parser) in /tmpfs/src/github/dotnet-docs-samples/commandlineutil/Lib/VerbMap.cs:line 85
   at GoogleCloudSamples.VideoIntelligence.Analyzer.Main(String[] args) in /tmpfs/src/github/dotnet-docs-samples/video/api/Analyze/Program.cs:line 171
   at GoogleCloudSamples.CommandLineRunner.Run(String[] arguments) in /tmpfs/src/github/dotnet-docs-samples/testutil/TestUtil.cs:line 136
   at GoogleCloudSamples.VideoIntelligence.AnalyzeTests.TestAnalyzeNoArgsSucceeds() in /tmpfs/src/github/dotnet-docs-samples/video/api/Test/Tests.cs:line 50
Analyze labels gs://demomaker/cat.mp4
```

**Comment by jskeet** [comment]
I can't reproduce this - the tests ran for me. (They took 3 minutes, but they ran.)
Does this happen every time, and have you reproduced it on multiple machines?

**Comment by SurferJeffAtGoogle** [comment]
It works correctly for me locally too.  It's only failing on Kokoro.  It might be an issue with the command-line parsing library.  It might be that memory is somehow corrupted.  Still investigating...

**Comment by SurferJeffAtGoogle** [comment]
I think it's the infinite loop referred to here:
https://github.com/commandlineparser/commandline/commit/95ded2dbcc5285302723e68221cd30a72444ba84
It's nothing to do with the video API.
