### ISSUE TITLE
Spanner C# Driver - NPE Exception.

### ISSUE THREAD

**Issue by alyaros** [GoogleCloudPlatform/google-cloud-dotnet#1794]
Code:
var spannerCommand =  spannerConnection.CreateInsertCommand("TableNameHere", spannerParameterCollection);
return await spannerCommand.ExecuteNonQueryAsync();

Error:

   at Google.Cloud.Spanner.V1.TransactionPool.SessionInfo.<CreateTransactionImplAsync>d__21.MoveNext() in C:\Users\benwu\spanner\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Spanner.V1\Google.Cloud.Spanner.V1\TransactionPool.cs:line 273
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.V1.TransactionPool.<BeginPooledTransactionAsync>d__5.MoveNext() in C:\Users\benwu\spanner\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Spanner.V1\Google.Cloud.Spanner.V1\TransactionPool.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.Data.SpannerConnection.<>c__DisplayClass68_0.<<BeginTransactionImplAsync>b__0>d.MoveNext() in C:\Users\benwu\spanner\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Spanner.Data\Google.Cloud.Spanner.Data\SpannerConnection.cs:line 728
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.Data.ExecuteHelper.<WithErrorTranslationAndProfiling>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.Data.EphemeralTransaction.<>c__DisplayClass5_0.<<ExecuteMutationsAsync>b__1>d.MoveNext() in C:\Users\benwu\spanner\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Spanner.Data\Google.Cloud.Spanner.Data\EphemeralTransaction.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.Data.ExecuteHelper.<WithErrorTranslationAndProfiling>d__2`1.MoveNext() in C:\Users\benwu\spanner\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Spanner.Data\Google.Cloud.Spanner.Data\ExecuteHelper.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.Data.SpannerCommand.<ExecuteMutationsAsync>d__53.MoveNext() in C:\Users\benwu\spanner\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Spanner.Data\Google.Cloud.Spanner.Data\SpannerCommand.cs:line 420
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NG.EntityFramework.Spanner.Storage.SpannerDatabase.<OnAdded>d__7.MoveNext() in C:\Users\alyaros\Downloads\main-20171224_orleans2\Data\NG.EntityFramework.Spanner\Storage\SpannerDatabase.cs:line 84

**Comment by jskeet** [comment]
Thanks for the report. Any other relevant information? What parameters are you supplying, for example?

**Comment by jskeet** [comment]
(I'll let Ben assign a priority when he's looked at it. Please bear with us if it takes a bit longer to diagnose over the holiday period... I know I'm not working again until January; I don't know if Ben is in the same situation.)

**Comment by alyaros** [comment]
looks like this problem arise only when I'm trying to perform multiple inserts. (It fails on the second insert)

**Comment by jskeet** [comment]
Could you provide a minimal but complete example that would help us reproduce this?

**Comment by benwulfe** [comment]
Also please provide the full exception message and text.  Sometimes you will get an exception creating a Session if you have supplied invalid arguments in your connection string.  A very common error is to use a capital letter for your database or instance -- which is illegal.  For example, connecting to database "Orders" instead of "orders"

**Comment by benwulfe** [comment]
alyaros@ does this still repro?
Possibly this was fixed with this fix? https://github.com/GoogleCloudPlatform/google-cloud-dotnet/pull/1650
There shouldnt be any way for a NPE to occur in the method given.

**Comment by alyaros** [comment]
Hey,
Sorry for the delay, took me some while to get to it.

Anyway, I have changed my implementation since - to overcome the issue mentioned above but mainly in order to avoid multiple round trips and so now on write I'm using the "Google.Cloud.Spanner.V1" For Write Flow and "Google.Cloud.Spanner.Data -Version 1.0.0" For Read flow.
This allows me both to enjoy the benefits of the new ADO Driver and also use more efficient Writes in Bulk.

For example  Write looks like that 
var commitResponse = await _spannerClient.CommitAsync(new CommitRequest
            {
                Mutations = { mutations },
                TransactionId = transaction.Id,
                SessionAsSessionName = session.SessionName
            }).ConfigureAwait(false);

and contains many Mutations in a single round trip to Spanner.

While Read Looks like:
        dbCommand = spannerConnection.CreateSelectCommand(this.CommandText, queryParameterCollection);                

                if (connection.CurrentTransaction != null)
                    dbCommand.Transaction = connection.CurrentTransaction.GetDbTransaction();

                if (connection.CommandTimeout != null)
                    dbCommand.CommandTimeout = (int)connection.CommandTimeout;

                var reader = dbCommand.ExecuteReader();

 
I also took a quick look over your alpha code and looks like we are following the same directions\path - after all there aren't much paths to take while writing yet another EF provider.. 
Hopefully, in the near future I'll able to use your "formal" code and offer\add some of my relevant code as Pull Request.

Currently, I'm working on Supporting Index usage. 
I'll add more details about it later in this thread, I assume it can be helpful for all of us.
Thanks!

**Comment by alyaros** [comment]
As For The Index Support I've tried to do something like this:

` public static class SpannerIndexSupport
{
public static IQueryable<TSource> WithIndex<TSource>(this IQueryable<TSource> query, string indexName)
        {
            var methodDefinition = typeof(SpannerIndexSupport).GetTypeInfo().GetMethods().Single(m => m.Name == "WithIndex");
            var method = methodDefinition.MakeGenericMethod(typeof(TSource));
            var args = new[] { query.Expression, Expression.Constant(indexName) };
            var expression = Expression.Call(null, method, args);
            return query.Provider.CreateQuery<TSource>(expression);
        }
    }
public class CustomAsyncQueryProvider : IAsyncQueryProvider { ... }
`

And The Activation is something like:
` using (var ctx = new AppDatabaseContext(connectionString)) { var postTag = ctx.PostTags.WithIndex("ABC").Where(x => x.TagId == 1).FirstOrDefault(); } `

Took the idea from Mongo-Linq Driver but couldn't make it work so far...
I'll be happy to hear some ideas if you might have about this topic..

**Comment by benwulfe** [comment]
If you manually create and specify a transaction for a SpannerCommand write, you will be able to write multiple times and only have it send one message to the server when you finally call CommitAsync() on the transaction.  If you only wish to avoid multiple trips to the server, you shouldn't need to drop down to V1.
Haven't had a look at index support yet.  Will try soon.  Thanks for the pointer.

**Comment by benwulfe** [comment]
you can find an example of insert SpannerCommands in a single ADO.NET transaction here:
https://github.com/benwulfe/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/SpannerStressTests.cs#L96

**Comment by alyaros** [comment]
Hey,
We changed our EF driver to use ADO for Read path and V1 for Write Path.
The problem I mentioned in this ticket was related to the Write Path via ADO which I'm no longer using - so I have no new input on this issue. If it does not occurred for others and based on the inputs above I think we close this ticket.

**Comment by jskeet** [comment]
Fine by me - we can always reopen it if anyone else reports a similar issue. Thanks for getting back to me.
