### ISSUE TITLE
LanguageServiceClient.Create(channel) throws a Grpc.Core.RpcException

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#1811]
This code:
```cs
            var credential = GoogleCredential.FromFile(jsonPath);
            var channel = new Grpc.Core.Channel(
                LanguageServiceClient.DefaultEndpoint.ToString(),
                credential.ToChannelCredentials());
            var client = LanguageServiceClient.Create(channel);
```

Throws this exception:
```
[xUnit.net 00:00:03.4792696]       Grpc.Core.RpcException : Status(StatusCode=Unauthenticated, Detail="Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.")
[xUnit.net 00:00:03.4805989]       Stack Trace:
[xUnit.net 00:00:03.4821124]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:03.4822241]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:03.4822684]            at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
[xUnit.net 00:00:03.4823112]            at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
[xUnit.net 00:00:03.4823722]            at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
[xUnit.net 00:00:03.4824483]         C:\Users\jon\Test\Projects\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Language.V1\Google.Cloud.Language.V1\LanguageServiceGrpc.cs(216,0): at Google.Cloud.Language.V1.LanguageService.LanguageServiceClient.AnalyzeSentiment(AnalyzeSentimentRequest request, CallOptions options)
[xUnit.net 00:00:03.4825079]         C:\chrisdunelm\gax-dotnet\releasebuild\src\Google.Api.Gax.Grpc\ApiCall.cs(27,0): at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__1(TRequest req, CallSettings cs)
[xUnit.net 00:00:03.4825634]         C:\chrisdunelm\gax-dotnet\releasebuild\src\Google.Api.Gax.Grpc\ApiCallRetryExtensions.cs(84,0): at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
[xUnit.net 00:00:03.4826134]         /tmpfs/src/github/dotnet-docs-samples/auth/AuthSample/Program.cs(362,0): at GoogleCloudSamples.CloudLibrary.AnalyzeSentiment(LanguageServiceClient client)
[xUnit.net 00:00:03.4826564]         /tmpfs/src/github/dotnet-docs-samples/auth/AuthSample/Program.cs(337,0): at GoogleCloudSamples.CloudLibrary.AuthExplicit(String projectId, String jsonPath)
[xUnit.net 00:00:03.4826976]         /tmpfs/src/github/dotnet-docs-samples/auth/AuthSample/Program.cs(379,0): at GoogleCloudSamples.AuthSample.ChooseAuthMethodAndInvoke(BaseOptions options, AuthLibrary library)
[xUnit.net 00:00:03.4827372]         /tmpfs/src/github/dotnet-docs-samples/auth/AuthSample/Program.cs(394,0): at GoogleCloudSamples.AuthSample.<>c.<Main>b__1_3(CloudOptions opts)
[xUnit.net 00:00:03.4827781]         /tmpfs/src/github/dotnet-docs-samples/auth/AuthSample/Program.cs(389,0): at GoogleCloudSamples.AuthSample.Main(String[] args)
[xUnit.net 00:00:03.4828135]         /tmpfs/src/github/dotnet-docs-samples/testutil/TestUtil.cs(136,0): at GoogleCloudSamples.CommandLineRunner.Run(String[] arguments)
[xUnit.net 00:00:03.4828817]         /tmpfs/src/github/dotnet-docs-samples/auth/AuthTest/AuthTest.cs(60,0): at GoogleCloudSamples.AuthTest.TestExplicit(String cmd)
```

Whereas this code, with GOOGLE_APPLICATION_CREDENTIALS set to the exact same path, succeeds:

```cs
            var client = LanguageServiceClient.Create();
```

See this PR for sample code and test failures:
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/418

**Comment by jskeet** [comment]
I'll test this today, but I expect this is because you haven't included any scopes. There are two options here:

- Specify scopes as documented [in the FAQ](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-non-default-credentials-for-grpc-based-apis)
- Upgrade to Grpc.Core version 1.8.0, where this problem goes away

The latter approach is what we're hoping to do over time by updating our own dependencies, but for now just adding a dependency on Grpc.Core and making sure it's version 1.8.0 should work. I'm going to test both of these paths work with LanguageServiceClient today.

**Comment by jskeet** [comment]
Just tested, and the first approach works. The code change is this:

```csharp
var credential = GoogleCredential.FromFile(jsonPath);
```

to this:

```csharp
var credential = GoogleCredential.FromFile(jsonPath)
    .CreateScoped(LanguageServiceClient.DefaultScopes);
```

Changing the Grpc.Core dependency *hasn't* worked for me, and I don't know why - I need to investigate that further.

**Comment by SurferJeffAtGoogle** [comment]
Thanks Jon!
