### ISSUE TITLE
I see uncaught exceptions in long-running Pub/Sub client.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#2037]
```
System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Grpc.Core.Internal.ChannelSafeHandle.CreateCall(CallSafeHandle parentCall, ContextPropagationFlags propagationMask, CompletionQueueSafeHandle cq, String method, String host, Timespec deadline, CallCredentialsSafeHandle credentials)
   at Grpc.Core.Internal.AsyncCall`2.CreateNativeCall(CompletionQueueSafeHandle cq)
   at Grpc.Core.Internal.AsyncCall`2.Initialize(CompletionQueueSafeHandle cq)
   at Grpc.Core.Internal.AsyncCall`2.StartDuplexStreamingCall()
   at Grpc.Core.Calls.AsyncDuplexStreamingCall[TRequest,TResponse](CallInvocationDetails`2 call)
   at Grpc.Core.DefaultCallInvoker.AsyncDuplexStreamingCall[TRequest,TResponse](Method`2 method, String host, CallOptions options)
   at Grpc.Core.Internal.InterceptingCallInvoker.AsyncDuplexStreamingCall[TRequest,TResponse](Method`2 method, String host, CallOptions options)
   at Google.Cloud.PubSub.V1.Subscriber.SubscriberClient.StreamingPull(CallOptions options)
   at Google.Api.Gax.Grpc.ApiBidirectionalStreamingCall.<>c__DisplayClass0_0`2.<Create>b__0(CallSettings cs)
   at Google.Api.Gax.Grpc.ApiBidirectionalStreamingCall`2.Call(CallSettings perCallCallSettings)
   at Google.Cloud.PubSub.V1.SubscriberServiceApiClientImpl.StreamingPull(CallSettings callSettings, BidirectionalStreamingSettings streamingSettings)
   at Google.Cloud.PubSub.V1.SubscriberClientImpl.SingleChannel.<StartAsync>d__18.MoveNext()
```

Here's the code:
https://github.com/SurferJeffAtGoogle/csharp-docs-samples/blob/sudoku/appengine/flexible/Sudokumb2.0/WebLib/PubsubGameBoardQueue.cs

**Comment by jskeet** [comment]
Assigned to Chris, but he's now OOO until April 9th.

How did you see the exception, and at what point? (For example, might this be on app shutdown?)

**Comment by hkedjour** [comment]
We have this issue from time to time. It comes after `SubscriberClient.StopAsync()` is called and something still active. We can see in the logs `Channel shutdown was called but there are still 1 active calls for that channel`.
Then -after few minutes in some cases-  the `StopAsync()` will raise the following exception  :
```csharp
"Depth": 0,
  "ClassName": "",
  "Message": "Shutdown has already been called",
  "Source": "Grpc.Core",
  "StackTraceString": "   at Grpc.Core.Internal.CompletionQueueSafeHandle.BeginOp()
   at Grpc.Core.Internal.CallSafeHandle.StartSendMessage(ISendCompletionCallback callback, Byte[] payload, WriteFlags writeFlags, Boolean sendEmptyInitialMetadata)
   at Grpc.Core.Internal.AsyncCallBase`2.SendMessageInternalAsync(TWrite msg, WriteFlags writeFlags)
   at Google.Api.Gax.Grpc.BufferedClientStreamWriter`1.Request.WriteTo(IClientStreamWriter`1 writer)
   at Google.Api.Gax.Grpc.BufferedClientStreamWriter`1.WriteAsyncImpl(T message, WriteOptions options, Boolean modifyOptions, Boolean throwOnError)
   at Google.Cloud.PubSub.V1.SubscriberClientImpl.SingleChannel.<Push>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.PubSub.V1.Tasks.TaskHelper.<>c__DisplayClass12_0.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.PubSub.V1.SubscriberClientImpl.SingleChannel.<StartAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.PubSub.V1.Tasks.Extensions.<>c__DisplayClass4_0.<<ConfigureAwaitHideErrors>g__Inner0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.PubSub.V1.Tasks.ForwardingAwaiter`1.GetResult()
   at Google.Cloud.PubSub.V1.Tasks.Extensions.<>c__DisplayClass1_0`1.<<ConfigureAwaitWithFinally>g__Inner0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.PubSub.V1.Tasks.ForwardingAwaiter`1.GetResult()
   at Google.Cloud.PubSub.V1.SubscriberClientImpl.<>c__DisplayClass18_0.<<StopAsync>b__1>d.MoveNext()",
```
What bothers me is that after `StopAsync` is called, we still receive messages. In our case, when we finish processing one message, we send another message to another queue. But unfortunately sending a message will fail with the exception `System.ObjectDisposedException: Safe handle has been closed`.

The `Safe handle has been closed` exception don't impact pub/sub only, but during the shutdown, I noticed also that one of our services that uses gRPC failed with same exception.

My guess, is that shutting down pub/sub message streaming will destroy all gRPC channels even the ones that were not related to pub/sub.

**Comment by chrisdunelm** [comment]
@hkedjour thanks for the error report.
Shutting down the subscriber by calling `StopAsync(...)` shuts down only the channels created for this subscriber; and should not be affecting any other gRPC channels. If it is, then this is a definite bug that needs fixing.
And `StopAsync(...)` should not throw the exception you're seeing. I'll look into this too.

It is correct that a few messages can be received after `StopAsync(...)` has been called; but, that should not affect sending a message.
How are you sending the message? Are you using an instance of `PublisherClient`, using the `PublishAsync(...)` method?

**Comment by hkedjour** [comment]
Yes, we are using the `PublisherClient.PublishAsync(...)` method. But not only Publishing messages is impacted. Here a call stack from calling our own service that uses grpc (during the shutdown):
```csharp

  "Message": "Shutdown has already been called",
  "Source": "Grpc.Core",
  "StackTraceString": "   at Grpc.Core.Internal.CompletionQueueSafeHandle.BeginOp()
   at Grpc.Core.Internal.CallSafeHandle.StartSendMessage(ISendCompletionCallback callback, Byte[] payload, WriteFlags writeFlags, Boolean sendEmptyInitialMetadata)
   at Grpc.Core.Internal.AsyncCallBase`2.SendMessageInternalAsync(TWrite msg, WriteFlags writeFlags)
   at ......Grpc.Chunks.<SendAsync>d__0`1.MoveNext()
```

**Comment by chrisdunelm** [comment]
How are you creating the Subscriber clients? Are you passing in your own `SubscriberServiceApiClient` instances to `SubscriberClient.Create(...)`; or are you using `SubscriberClient.CreateAsync(...)`?

**Comment by chrisdunelm** [comment]
@hkedjour, @SurferJeffAtGoogle [Google.Cloud.Pubsub.V1 v1.0.0-beta18](https://www.nuget.org/packages/Google.Cloud.PubSub.V1/1.0.0-beta18) has just been released. Please can you upgrade to this version and see if the `System.ObjectDisposedException: Safe handle has been closed` still re-occurs?

**Comment by chrisdunelm** [comment]
Closing as this is likely fixed by [Google.Cloud.PubSub.V1 1.0.0-beta19](https://www.nuget.org/packages/Google.Cloud.PubSub.V1/1.0.0-beta19). Please leave a comment if this is still being seen, so we can re-open.
