### ISSUE TITLE
Strange Exception

### ISSUE THREAD

**Issue by aptly-io** [GoogleCloudPlatform/google-cloud-dotnet#2177]
The sample code below fails in an UWP with the following exception but succeeds on Windows Desktop (a Forms app) on the ```new Channel =``` statement. I use the channel to authorize a ServiceAccount to access Google's Stackdriver logger service.

Is this my misunderstanding of UWP or some library incompatibility that is easy to fix?

```
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'System.Runtime.Loader.AssemblyLoadContext' from assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
  Source=Grpc.Core
  StackTrace:
   at Grpc.Core.GrpcEnvironment.ShutdownHooks.Register()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Techsoft.Physical.Access.StackdriverLogger.<>c__DisplayClass10_0.<.ctor>b__0() in C:\Users\francis1\dev\DiskmanDemo\Unlocker\WinUnlocker\PhysicalAccess\Nfc\Nfc\StackdriverLogger.cs:line 70
   at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c__DisplayClass6_0.<GetActionLogDelegate>b__0()
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

I used these nuget packages:
- Microsoft.NETCore.UniversalWindowsPlatform v6.1.0 (and v6.2.0-Previewxxx) [only for the UWP]
- Google.Cloud.Logging.V2 v2.1.0

(I actually tried with different combinations of library versions on the UWP)

Sample:
```csharp
var bytes = readFile("credential.p12");
var certificate = new X509Certificate2(bytes, "notasecret", X509KeyStorageFlags.Exportable);
var credentialP12 = new ServiceAccountCredential(
    new ServiceAccountCredential.Initializer(ACCOUNT_ID) {
        Scopes = CREDENTIAL_SCOPES,
    }.FromCertificate(certificate));
var channelCredentials = credentialP12.ToChannelCredentials();

# Here the exception occurs when ran in an UWP program
var channel = new Channel(LoggingServiceV2Client.DefaultEndpoint.ToString(), channelCredentials);
```

**Comment by jskeet** [comment]
I'm afraid UWP isn't a supported platform for these libraries. See details of our supported platforms [here](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/guides/platforms.html).

While we would *like* to support UWP, it isn't feasible right now.

**Comment by aptly-io** [comment]
@jskeet thanks, do you know of an alternative to log entries to the stackdriver logging from C# UWP? The app will only run on x64 platform ...
