### ISSUE TITLE
Deadline Exceeded

### ISSUE THREAD

**Issue by haf** [GoogleCloudPlatform/google-cloud-dotnet#2249]
What does this mean?

```
api_1         | [12:38:13 WRN] Exception from supervised job, restarting in 102 ms. <Logary.Target(stackdriver)>
api_1         | Grpc.Core.RpcException: Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")
api_1         |   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
api_1         |   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
api_1         |   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
api_1         |   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
api_1         |   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
api_1         |   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
api_1         |   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
api_1         |   at Google.Cloud.Logging.V2.LoggingServiceV2.LoggingServiceV2Client.WriteLogEntries(WriteLogEntriesRequest request, CallOptions options)
api_1         |   at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)
api_1         |   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
api_1         |   at Logary.Targets.Stackdriver.Impl.u2x@1(State state, FSharpList`1 entries, Unit unitVar0)
api_1         |   at Logary.Targets.Stackdriver.Impl.writeBatch@247.Do()
api_1         |   at Hopac.Core.JobIsolate`1.DoJob(Worker& wr, Cont`1 xK)
api_1         |   at Hopac.Core.Worker.Run(Scheduler sr, Int32 me)
```

**Comment by chrisdunelm** [comment]
From a stackdriver point of view, It means that an RPC to the stackdriver logging service was performed, but could not be completed by the server before the client-specified timeout expired.

I see you're using a third-party Logary package to access stackdriver logging, so it's not something we can help with directly. I would suggest looking at how the logary stackdriver integration handles errors, retries and timeouts.

**Comment by haf** [comment]
I built Logary, and it restarts its target upon exceptions like these; but we drop the batch of messages.

But that's not the question, but;

 1. Is this the expected behaviour to expose to the caller?
 2. Is this an error that I am to retry sending to Stackdriver?
 3. What further errors are supposed to be retries? A list, please.

**Comment by chrisdunelm** [comment]
If you're creating `LoggingServiceV2Client` with default settings, then calling `LoggingServiceV2Client.WriteLogEntries(...)` does not use retry. This is because `WriteLogEntries` is non-idempotent, so the library by default does the safe thing of returned any errors. So yes, it is expected that you may see a DEADLINE_EXCEEDED error.

What deadline are you using? The default [is 20 seconds](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingServiceV2Client.cs#L123).

It is up to you whether you retry on a DEADLINE_EXCEEDED error. You may end up with duplicate log entries, but that may be preferable to not recording the log entries at all.

For idempotent calls the [default is to retry on errors](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingServiceV2Client.cs#L76): `DeadlineExceeded`, `Internal`, and `Unavailable`. You may wish to consider retrying on these.

**Comment by haf** [comment]
[Default settings indeed](https://github.com/logary/logary/blob/master/src/targets/Logary.Targets.Stackdriver/Target_Stackdriver.fs#L240) — is that not recommended for this use-case?

Logs generally don't have side-effects, and besides that; doesn't the library generate an insert hash/id as a request id that can be unified within a time window?

**Comment by chrisdunelm** [comment]
The library does not automatically generate an insert id for each log entry.
You can do this in your own code, by setting the [`InsertId`](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LogEntry.cs#L289) property uniquely for each log entry; then you can enable retry safely.
