### ISSUE TITLE
[Google.Cloud.Datastore.V1]: System.ObjectDisposedException

### ISSUE THREAD

**Issue by kkrasouski** [GoogleCloudPlatform/google-cloud-dotnet#2285]
Good day,

We heavily use Google.Cloud.Datastore.V1 library for Google Datastore integration and are facing the following issue quite regularly (full stack trace is attached
[stacktrace.txt](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/files/2136035/stacktrace.txt)
):
ystem.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Grpc.Core.Internal.ChannelSafeHandle.CreateCall(CallSafeHandle parentCall, ContextPropagationFlags propagationMask, CompletionQueueSafeHandle cq, String method, String host, Timespec deadline, CallCredentialsSafeHandle credentials)
   at Grpc.Core.Internal.AsyncCall`2.CreateNativeCall(CompletionQueueSafeHandle cq)
   at Grpc.Core.Internal.AsyncCall`2.Initialize(CompletionQueueSafeHandle cq)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCallAsync(TRequest msg)
   at Grpc.Core.Calls.AsyncUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.Datastore.V1.Datastore.DatastoreClient.CommitAsync(CommitRequest request, CallOptions options)

We do not see any misuses from our side, so could you please help with this issue?

We've already performed upgrade to the latest available version and still see the issue.

**Comment by jskeet** [comment]
Could you give more details of how you're using the API? In particular, are you managing your own channels and credentials, or just using the default credentials?

Could you elaborate on what you mean by "quite regularly"? Are you able to reproduce this in a reliable fashion? (A small example which reproduced it reliably, even if it took several hours to do so, would be *really* helpful.)

cc @jtattermusch in case this is a gRPC issue.

**Comment by kkrasouski** [comment]
Answering your questions:
A) We just use DatastoreDb wrapped in a quite simple wrapper class from our side. 
 - initialization of DatastoreDb instance happens during Asp .Net Core Startup ConfigureServices(IServiceCollection services) and just calls DatastoreDb.Create(SomeProjectId, SomeNamespaceId); and then being injected into aforementioned wrapper class;
 - No own channels or credentials;
 - From the whole set of DatastoreDb class we utilize only LookupAsync(Key key, null, null) and UpsertAsync(params Entity[] entities).

B) Quite regularly is 100+ hits per day for failures with this particular exception.

C) Unfortunately not, nothing at the moment. Firstly we planned to check with you whether you have any clue/idea on why it happens.

**Comment by jskeet** [comment]
Hmm. As we haven't done a release of Google.Cloud.Datastore.V1 recently, you've probably got quite an old Grpc.Core dependency - 1.7.1 maybe.

Could you try updating to Grpc.Core 1.12.0 (with no other changes) and see if that affects things?

Have you noticed any patterns in this, e.g. an exception coming after a period of inactivity?

**Comment by chrisdunelm** [comment]
(Just for information, this error and stacktrace look very similar to #2037)

**Comment by kkrasouski** [comment]
We deployed a new API version with Grpc.Core dependency upgraded to 1.12.0 (the latest available) and what I see up to the moment is that the issue still happens with the same frequency.

**Comment by jskeet** [comment]
Thanks for the update. One interesting difference between this and #2037 is that this isn't a streaming call.

**Comment by jskeet** [comment]
@kkrasouski: Given Chris's work on #2243 is it possible that this happens only when ASP.NET Core is shutting down?

**Comment by jtattermusch** [comment]
I looked at the stack trace and it seems that the exception is coming from this line:
https://github.com/grpc/grpc/blob/252d3f3b460cf56db2e30d68e566a00cef0304eb/src/csharp/Grpc.Core/Internal/AsyncCall.cs#L404

what it is doing is taking an channel's safe handle and creating a call on it. The exception is thrown because the safe handle has already been disposed. That very likely means that the channel was already shutdown when trying to create the call - which in itself is not unexpected, but I agree that error message is pretty cryptic (and we should improve that).

Without having knowledge of your application it is hard for me to know why the channel has been shutdown (perhaps you invoked channel.ShutdownAsync() yourself, perhaps this an automated shutdown by grpc's shutdown hook).

**Comment by kkrasouski** [comment]
@jskeet, we're continuing investigation from our side to provide some clue for you. But at the moment I can't say something with enough level of certainty.

@jtattermusch , commenting on your last paragraph - we don't manage channels ourselves (see the 3rd comment from me), so it's most probably the 2nd case you mentioned. Any workaround/advice you could provide?

**Comment by jskeet** [comment]
Assuming you're still seeing this, could you try to add an explicit dependency on Grpc.Core 1.13.1? If this *is* a problem with shutdown, that should fix it.

**Comment by kkrasouski** [comment]
Let us try, thank you!
