### ISSUE TITLE
Datastore calls fail to authenticate with service account.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#294]
The same credentials work for REST-based class libraries.

I built a simple command line sample here:
https://github.com/SurferJeffAtGoogle/csharp-docs-samples/tree/datastoreVeneerBug

Demo:
```
PS C:\Users\rennie\gitrepos\dotnet-docs-samples> gci env: | where {$_.Name -like "google_*"}

Name                           Value
----                           -----
GOOGLE_APPLICATION_CREDENTIALS C:\USERS\rennie\Downloads\bookshelf-dotnet-dc82be9a4dde.json
GOOGLE_BUCKET                  bookshelf-dotnet
GOOGLE_PROJECT_ID              bookshelf-dotnet


PS C:\Users\rennie\gitrepos\dotnet-docs-samples\storage\api> cd .\datastore\api\DatastoreSample\bin\Debug
PS C:\Users\rennie\gitrepos\dotnet-docs-samples\datastore\api\DatastoreSample\bin\Debug> .\DatastoreSample.exe apiary
Using credentials from C:\USERS\rennie\Downloads\bookshelf-dotnet-dc82be9a4dde.json.
Description: Steinbeck's first major critical and commercial success, TORTILLA FLAT is also his funniest novel. Danny is
 a paisano, descended from the original Spanish settlers who arrived in Monterey, California, centuries before. He value
s friendship abovemoney and possessions, so that when he suddently inherits two houses, Danny is quick to offer shelter
to his fellow gentlemen of the road. Their love of freedom and scorn for material things draw them into daring and often
 hilarious adventures. Until Danny, tiring of his new reponsibilities, suddenly disappears...
Title: Tortilla Flat
Author: John Steinbeck
ImageUrl: https://www.googleapis.com/download/storage/v1/b/bookshelf-dotnet/o/5636318331666432?generation=14592066659660
00&alt=media
PublishedDate:
PS C:\Users\rennie\gitrepos\dotnet-docs-samples\datastore\api\DatastoreSample\bin\Debug> .\DatastoreSample.exe veneer
Using credentials from C:\USERS\rennie\Downloads\bookshelf-dotnet-dc82be9a4dde.json.

Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Unauthenticated, Detail="Request had invalid authenticati
on credentials.")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions optio
ns, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, Cal
lOptions options, TRequest request)
   at Google.Datastore.V1Beta3.Datastore.DatastoreClient.RunQuery(RunQueryRequest request, CallOptions options)
   at Google.Api.Gax.ApiCallExtensions.<>c__DisplayClass0_0`3.<MapArg>b__0(A a, CallSettings callSettings)
   at Google.Api.Gax.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSe
ttings)
   at Google.Api.Gax.ApiCallExtensions.<>c__DisplayClass0_0`3.<MapArg>b__0(A a, CallSettings callSettings)
   at Google.Api.Gax.ApiCall`2.<>c__DisplayClass6_0.<Sync>b__0(CallSettings callSettings)
   at Google.Api.Gax.ApiCall`2.Call[T](TRequest request, CallSettings perCallCallSettings, Func`2 fn)
   at Google.Api.Gax.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Datastore.V1Beta3.QueryStreamer.<Sync>d__7.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at DatastoreSample.Program.Main(String[] args) in C:\Users\rennie\gitrepos\dotnet-docs-samples\datastore\api\Datastor
eSample\Program.cs:line 59
PS C:\Users\rennie\gitrepos\dotnet-docs-samples\datastore\api\DatastoreSample\bin\Debug>
```

**Comment by jskeet** [comment]
It looks like this is due to us not using `CreateScoped` when constructing the credentials in https://github.com/googleapis/gax-dotnet/blob/master/src/Google.Api.Gax/ChannelPool.cs

I was under the impression that scoping wasn't required for gRPC in this situation, but I could be wrong. Will ask for more advice from those in the know...

**Comment by jskeet** [comment]
I've looked into this a bit more, and it's not Datastore-specific - it affects all gRPC-based APIs. I was under the impression that `CreateScoped` was not required for gRPC calls... we're still looking into whether that's a fault in my understanding, or some other auth code.

If we *do* need to fix this, we should:

- Make the `ChannelPool` constructor accept a set of scopes and apply them when obtaining credentials
- Change the code generator to pass those scopes in when it constructs a channel pool... importantly, this probably means reordering the code to declare `DefaultScopes` *before* `s_ChannelPool`

Note that this would be a breaking change in GAX, unless we maintain a parameterless constructor as well. (We could use a parameter array to maintain *source* compatibility without breaking *binary* compatibility, admittedly.)

// cc @chrisdunelm as he may end up doing this :)

**Comment by jskeet** [comment]
This is fixed by the changes referenced above. The fix will be in the beta-02 package when we build that. In the meantime, users can use the CI000174 build available from our public myget feed: https://www.myget.org/gallery/google-dotnet-public
