### ISSUE TITLE
RunQuery throws exception with no error information.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#304]
Here's [the code](https://github.com/SurferJeffAtGoogle/csharp-docs-samples/blob/datastoreAsTest/datastore/api/DatastoreTest.cs#L349):

```
            Query query = new Query("Task")
            {
                Filter = new Filter()
                {
                    CompositeFilter = new CompositeFilter()
                    {
                        Op = CompositeFilter.Types.Operator.And
                    }
                },
            };
            query.Filter.CompositeFilter.Filters.Add(new Filter()
            {
                PropertyFilter = new PropertyFilter()
                {
                    Op = PropertyFilter.Types.Operator.Equal,
                    Property = new PropertyReference("done"),
                    Value = false,
                }
            });
            query.Filter.CompositeFilter.Filters.Add(new Filter()
            {
                PropertyFilter = new PropertyFilter()
                {
                    Op = PropertyFilter.Types.Operator.GreaterThanOrEqual,
                    Property = new PropertyReference("priority"),
                    Value = 4,
                }
            });
            query.Order.Add(new PropertyOrder()
            {
                Property = new PropertyReference("priority"),
                Direction = PropertyOrder.Types.Direction.Descending
            });
            // [END basic_query]
            Assert.AreEqual(1,_db.RunQuery(query).Count());
```

And the error message:

```
Test Name:  TestBasicQuery
Test FullName:  GoogleCloudSamples.DatastoreTest.TestBasicQuery
Test Source:    C:\Users\rennie\gitrepos\dotnet-docs-samples\datastore\api\DatastoreTest.cs : line 350
Test Outcome:   Failed
Test Duration:  0:00:01.7877132

Result StackTrace:  
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Datastore.V1Beta3.Datastore.DatastoreClient.RunQuery(RunQueryRequest request, CallOptions options)
   at Google.Api.Gax.ApiCallExtensions.<>c__DisplayClass0_0`3.<MapArg>b__0(A a, CallSettings callSettings)
   at Google.Api.Gax.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.ApiCallExtensions.<>c__DisplayClass0_0`3.<MapArg>b__0(A a, CallSettings callSettings)
   at Google.Api.Gax.ApiCall`2.<>c__DisplayClass6_0.<Sync>b__0(CallSettings callSettings)
   at Google.Api.Gax.ApiCall`2.Call[T](TRequest request, CallSettings perCallCallSettings, Func`2 fn)
   at Google.Api.Gax.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Datastore.V1Beta3.QueryStreamer.<Sync>d__7.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at GoogleCloudSamples.DatastoreTest.TestBasicQuery() in C:\Users\rennie\gitrepos\dotnet-docs-samples\datastore\api\DatastoreTest.cs:line 387
Result Message: 
Test method GoogleCloudSamples.DatastoreTest.TestBasicQuery threw exception: 
Grpc.Core.RpcException: Status(StatusCode=FailedPrecondition, Detail="")

```

**Comment by jskeet** [comment]
This is now fixed - the error message isn't ideal (it's in HTML) but it's informative:

```out
Detail="no matching index found. recommended index is:<br/>- kind: Task<br/>  properties:<br/>  - name: done<br/>  - name: priority<br/>    direction: desc<br/>"
```
