### ISSUE TITLE
Projection queries fail with no error information.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#306]
The code:

```
            Query query = new Query("Task")
            {
                Projection = { "priority", "percent_complete" }
            };
            // [END projection_query]
            Assert.IsFalse(IsEmpty(_db.RunQuery(query)));
```

The error:

```
Test Name:  TestProjectionQuery
Test FullName:  GoogleCloudSamples.DatastoreTest.TestProjectionQuery
Test Source:    C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\datastore\api\DatastoreTest.cs : line 491
Test Outcome:   Failed
Test Duration:  0:00:01.2299546

Result StackTrace:  
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Datastore.V1Beta3.Datastore.DatastoreClient.RunQuery(RunQueryRequest request, CallOptions options)
   at Google.Api.Gax.ApiCallExtensions.<>c__DisplayClass0_0`3.<MapArg>b__0(A a, CallSettings callSettings)
   at Google.Api.Gax.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.ApiCallExtensions.<>c__DisplayClass0_0`3.<MapArg>b__0(A a, CallSettings callSettings)
   at Google.Api.Gax.ApiCall`2.<>c__DisplayClass6_0.<Sync>b__0(CallSettings callSettings)
   at Google.Api.Gax.ApiCall`2.Call[T](TRequest request, CallSettings perCallCallSettings, Func`2 fn)
   at Google.Api.Gax.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Datastore.V1Beta3.QueryStreamer.<Sync>d__7.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at GoogleCloudSamples.DatastoreTest.IsEmpty(DatastoreQueryResults results) in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\datastore\api\DatastoreTest.cs:line 349
   at GoogleCloudSamples.DatastoreTest.TestProjectionQuery() in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\datastore\api\DatastoreTest.cs:line 499
Result Message: 
Test method GoogleCloudSamples.DatastoreTest.TestProjectionQuery threw exception: 
Grpc.Core.RpcException: Status(StatusCode=FailedPrecondition, Detail="")


```

**Comment by jskeet** [comment]
Right - I suspect this is due to the fields not being indexed. I see the same thing in my snippets. There are three issues here:

- I haven't explicitly marked the fields as unindexed, so based on the [documentation](https://cloud.google.com/datastore/docs/concepts/queries#limitations_on_projections) I'd expect it to be okay.
- The RPC exception doesn't have any detail
- There's no way of configuring the index through the API as far as I can tell, which is a bigger issue

Will raise these internally with the Datastore team - we can't really address any of them in the client library.

**Comment by jskeet** [comment]
The error message is now included:

```txt
Detail="no matching index found. recommended index is:<br/>- kind: Task<br/>  properties:<br/>  - name: percent_complete<br/>  - name: priority<br/>"
```
