### ISSUE TITLE
RunQuery fails, even though necessary indexes exist.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#346]
Here's my index.yaml;

```
# Deploy with gcloud datastore create-indexes index.yaml
indexes:
- kind: Task
  properties:
  - name: category
    direction: asc
  - name: priority
    direction: asc
  - name: created
    direction: asc
```

And my code:

```
            Query query = new Query("Task")
            {
                Projection = { "category", "priority" },
                DistinctOn = { "category", "priority" },
                Order = { { "category", PropertyOrder.Types.Direction.Ascending},
                    {"priority", PropertyOrder.Types.Direction.Ascending } }
            };
            // [END distinct_query]
            Assert.False(IsEmpty(_db.RunQuery(query)));
```

And I still get this exception:

```
Test Name:  GoogleCloudSamples.DatastoreTest.TestDistinctQuery
Test FullName:  GoogleCloudSamples.DatastoreTest.TestDistinctQuery
Test Source:    C:\Users\rennie\gitrepos\dotnet-docs-samples\datastore\api\DatastoreTest.cs : line 554
Test Outcome:   Failed
Test Duration:  0:00:00.254

Result StackTrace:  
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Datastore.V1Beta3.Datastore.DatastoreClient.RunQuery(RunQueryRequest request, CallOptions options)
   at Google.Api.Gax.ApiCallExtensions.<>c__DisplayClass0_0`3.<MapArg>b__0(A a, CallSettings callSettings)
   at Google.Api.Gax.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.ApiCallExtensions.<>c__DisplayClass0_0`3.<MapArg>b__0(A a, CallSettings callSettings)
   at Google.Api.Gax.ApiCall`2.<>c__DisplayClass6_0.<Sync>b__0(CallSettings callSettings)
   at Google.Api.Gax.ApiCall`2.Call[T](TRequest request, CallSettings perCallCallSettings, Func`2 fn)
   at Google.Api.Gax.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Datastore.V1Beta3.QueryStreamer.<Sync>d__7.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at GoogleCloudSamples.DatastoreTest.IsEmpty(DatastoreQueryResults results) in C:\Users\rennie\gitrepos\dotnet-docs-samples\datastore\api\DatastoreTest.cs:line 358
   at GoogleCloudSamples.DatastoreTest.TestDistinctQuery() in C:\Users\rennie\gitrepos\dotnet-docs-samples\datastore\api\DatastoreTest.cs:line 565
Result Message: Grpc.Core.RpcException : Status(StatusCode=Internal, Detail="{"created":"@1472765097.981000000","description":"RST_STREAM","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\frame_rst_stream.c","file_line":107,"http2_error":2}")
```

**Comment by jskeet** [comment]
Patrick, do you have any insight about this?

**Comment by pcostell** [comment]
This isn't the appropriate index for the query. You'll need to define in your `index.yaml` file:

```
# Deploy with gcloud datastore create-indexes index.yaml
indexes:
- kind: Task
  properties:
  - name: category
    direction: asc
  - name: priority
    direction: asc
```

In Cloud Datastore, you can't "overspecify" your index because Cloud Datastore indexes are sparse. So if in this case an entity didn't have the `created` property it would not appear in the `(category, priority, created)` index so we wouldn't correctly answer your query.

**Comment by pcostell** [comment]
Also, I'd recommend running your code against the Cloud Datastore Emulator using the `gcloud beta emulators datastore start` command. This will create an index.yaml file for all the queries you run.

**Comment by SurferJeffAtGoogle** [comment]
That fails:
PS C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\language\api>
gcloud beta emulators datastore start
Executing: cmd /c C:\Users\Jeffrey Rennie\AppData\Local\Google\Cloud
SDK\google-cloud-sdk\platform\gcd\gcd.cmd create --
project_id=bookshelf-dotnet C:\Users\Jeffrey
Rennie\AppData\Roaming\gcloud-test\emulators\datastore
[datastore] 'C:\Users\Jeffrey' is not recognized as an internal or external
command,
[datastore] operable program or batch file.
ERROR: (gcloud.beta.emulators.datastore.start) Unable to prepare the data
directory for the emualtor
PS C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\language\api>

**Comment by jskeet** [comment]
Where are we with this? It doesn't feel like it's a bug for this repo, really...
