### ISSUE TITLE
Google Cloud Storage: System.ArgumentException : The Acl property of the object to update is null

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#477]
I get this exception with this code:

```
        private void MakePublic(string bucketName, string objectName)
        {
            var storage = StorageClient.Create();
            var storageObject = storage.GetObject(bucketName, objectName);
            // storageObject.Acl = storageObject.Acl ?? new List<ObjectAccessControl>();
            storage.UpdateObject(storageObject, new UpdateObjectOptions
            {
                PredefinedAcl = PredefinedObjectAcl.PublicRead
            });
        }
```

Uncommenting the line in the middle yields no more exception.

```
Test Name:  GoogleCloudSamples.QuickStartTest.TestMakePublic
Test FullName:  GoogleCloudSamples.QuickStartTest.TestMakePublic
Test Source:    C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\storage\api-veneer\QuickStartTest\QuickStartTest.cs : line 230
Test Outcome:   Failed
Test Duration:  0:00:03.304

Result StackTrace:  
at Google.Storage.V1.StorageClientImpl.CreateUpdateObjectRequest(Object obj, UpdateObjectOptions options)
   at Google.Storage.V1.StorageClientImpl.UpdateObject(Object obj, UpdateObjectOptions options)
   at GoogleCloudSamples.QuickStart.MakePublic(String bucketName, String objectName) in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\storage\api-veneer\QuickStart\Program.cs:line 163
   at GoogleCloudSamples.QuickStart.Run(String[] args) in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\storage\api-veneer\QuickStart\Program.cs:line 258
   at GoogleCloudSamples.BaseTest.Run(String[] arguments) in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\storage\api-veneer\QuickStartTest\QuickStartTest.cs:line 42
   at GoogleCloudSamples.QuickStartTest.TestMakePublic() in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\storage\api-veneer\QuickStartTest\QuickStartTest.cs:line 246
Result Message: 
System.ArgumentException : The Acl property of the object to update is null
Parameter name: obj
```

**Comment by jskeet** [comment]
You need to fetch the "full" view when you call GetObject.
However, I *may* be able to remove this check now, as I believe the server side has changed... but I'll have a look tomorrow.

**Comment by jskeet** [comment]
Obsolete now - the restriction has been removed in #554.
