### ISSUE TITLE
RPCs with CallSettings.Timing always fail with StatusCode=DeadlineExceeded.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#504]
The code in this test:
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/compare/retryFails?expand=1

Always fails with:
```
Test Name:	GoogleCloudSamples.PubsubTest.TestRpcRetry
Test FullName:	GoogleCloudSamples.PubsubTest.TestRpcRetry
Test Source:	C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\pubsub\api\PubsubTest.cs : line 351
Test Outcome:	Failed
Test Duration:	0:00:16.962

Result StackTrace:	
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Pubsub.V1.Subscriber.SubscriberClient.CreateSubscription(Subscription request, CallOptions options)
   at Google.Api.Gax.ApiCallExtensions.<>c__DisplayClass0_0`3.<MapArg>b__0(A a, CallSettings callSettings)
   at Google.Api.Gax.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.ApiCallExtensions.<>c__DisplayClass0_0`3.<MapArg>b__0(A a, CallSettings callSettings)
   at Google.Api.Gax.ApiCall`2.<>c__DisplayClass6_0.<Sync>b__0(CallSettings callSettings)
   at Google.Api.Gax.ApiCall`2.Call[T](TRequest request, CallSettings perCallCallSettings, Func`2 fn)
   at Google.Api.Gax.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Pubsub.V1.SubscriberClientImpl.CreateSubscription(String name, String topic, PushConfig pushConfig, Int32 ackDeadlineSeconds, CallSettings callSettings)
   at GoogleCloudSamples.PubsubTest.RpcRetry(String topicId, String subscriptionId, PublisherClient publisher, SubscriberClient subscriber) in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\pubsub\api\PubsubTest.cs:line 228
   at GoogleCloudSamples.PubsubTest.TestRpcRetry() in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\pubsub\api\PubsubTest.cs:line 354
Result Message:	Grpc.Core.RpcException : Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")

```

**Comment by jskeet** [comment]
One point to note in passing: if it's worth having a "maximum count of retries" we should put that in RetrySettings itself.

**Comment by jskeet** [comment]
Another point to note: this code won't compile when we've got the new GAX running again - the settings are immutable.

But other than that, it looks like it *should* be okay.

Assigning @chrisdunelm to have a look... I may give this a try with the updated code to see if I can figure it out.

**Comment by jskeet** [comment]
Looking at the code again, it's not clear what you're expecting to happen here - in particular, before this test started, did the topic exist? If not, I'd expect a failed with StatusCode=NotFound.

After creating the topic, the broadly equivalent new code worked for me - although I explicitly specified a MaxTimeout and an Expiration:

```csharp
        static CallSettings CreateRetryCallSettings(int tryCount)
        {
            var backoff = new BackoffSettings(TimeSpan.FromMilliseconds(500), TimeSpan.FromMilliseconds(5000), 2);
            return CallSettings.FromCallTiming(CallTiming.FromRetry(new RetrySettings(backoff, backoff, Expiration.None,
                (RpcException e) => e.Status.StatusCode != StatusCode.AlreadyExists && --tryCount > 0,
                RetrySettings.NoJitter)));
        }
```

It's not clear why you'd want to retry the operation if the subscription (or topic) already exists - surely it's not going to succeed later.

My guess is that the deadline error you ran into was due to a single RPC taking more than 500ms, and so being cancelled by the client side. Hard to know for sure though.

**Comment by SurferJeffAtGoogle** [comment]
Delay, MaxDelay, Expiration, TotalExpiration....

I can't make sense of all these parameters from the documentation.  I can't paint a mental picture of the loop and what each parameter does.

**Comment by SurferJeffAtGoogle** [comment]
All I want to say is, "try three times."  And that is very difficult with the current API.

**Comment by SurferJeffAtGoogle** [comment]
Rather: "try 3 times, but stop retrying if the status code is AlreadyExists."

**Comment by jskeet** [comment]
But "try three times" doesn't express anything about how long you're prepared for each operation to take, or how long to delay between attempts, or how long you're prepared for the overall operation to take - that's what those values are about. We can definitely improve the docs, of course.

It does sound like it would be worth adding a "max # attempts" to the configuration though.

**Comment by SurferJeffAtGoogle** [comment]
I have something that works now:
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/compare/retryFails?expand=1

**Comment by SurferJeffAtGoogle** [comment]
Can we provide default values for all those operation timeouts?

**Comment by jskeet** [comment]
They vary by call. We provide a set of (hopefully reasonable) defaults for each specific call, so maybe the thing to do is make it easy to create a new RetrySettings with a specific number of attempts and/or filter.

**Comment by jskeet** [comment]
Are you still able to reproduce this with the latest packages? (I don't think I ever quite got to the bottom of what the preconditions were for your sample.)

**Comment by jskeet** [comment]
Ping for recent repro. (Unless you're blocked on #595 of course. Chris and I will add some more docs for settings.)
