### ISSUE TITLE
LongRunning Client.GetOperation() fails with async speech operation name.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#604]
Sample code here:
https://github.com/SurferJeffAtGoogle/csharp-docs-samples/blob/f219a7cafd26b64212574ab0e44ab2d6134477bc/speech/api/TranscribeAsync/Program.cs

Yields this error:
```
Test Name:	GoogleCloudSamples.TranscribeAsyncTest.TranscribeAudio
Test FullName:	GoogleCloudSamples.TranscribeAsyncTest.TranscribeAudio
Test Source:	C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\speech\api\TranscribeAsyncTest\TranscribeAsyncTest.cs : line 51
Test Outcome:	Failed
Test Duration:	0:00:32.902

Result StackTrace:	
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Longrunning.Operations.OperationsClient.GetOperation(GetOperationRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.<>c__DisplayClass6_0.<Sync>b__0(CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.Call[T](TRequest request, CallSettings perCallCallSettings, Func`2 fn)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Longrunning.OperationsClientImpl.GetOperation(String name, CallSettings callSettings)
   at GoogleCloudSamples.TranscribeAsync.Main(String[] args) in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\speech\api\TranscribeAsync\Program.cs:line 48
   at GoogleCloudSamples.CommandLineRunner.Run(String[] arguments) in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\testutil\TestUtil.cs:line 107
   at GoogleCloudSamples.TranscribeAsyncTest.Run(String[] arguments) in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\speech\api\TranscribeAsyncTest\TranscribeAsyncTest.cs:line 38
   at GoogleCloudSamples.TranscribeAsyncTest.TranscribeAudio() in C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\speech\api\TranscribeAsyncTest\TranscribeAsyncTest.cs:line 52
Result Message:	Grpc.Core.RpcException : Status(StatusCode=Unknown, Detail="")
```

Looking at the asyncResponse:
`+		asyncResponse	{{ "name": "2592828109219406248" }}	Google.Longrunning.Operation`

**Comment by jskeet** [comment]
Right, that code won't work because `OperationsClient` needs to be tied to the gRPC channel that the Speech API uses. Basically we still need to overhaul the Speech client to expose the LRO part.

If you really want to work on this right now, you could manually create a channel, and pass that to both the `SpeechClient.Create` and `OperationsClient.Create` methods - but I'd wait if you possibly can.

**Comment by SurferJeffAtGoogle** [comment]
I'll wait.  When the speech client is ready, please close this bug to signal me to write the sample.

**Comment by jskeet** [comment]
v1.0.0-alpha03 is now on nuget :)
