### ISSUE TITLE
BigQuery internal exception while converting repeated fields (complex model)

### ISSUE THREAD

**Issue by mantas-paziura** [GoogleCloudPlatform/google-cloud-dotnet#660]
Stack trace:
```
{System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'System.String'.
   at Google.Cloud.BigQuery.V2.BigQueryRow.ConvertSingleValue(Object rawValue, TableFieldSchema field)
   at Google.Cloud.BigQuery.V2.BigQueryRow.ConvertRecord(JObject record, TableFieldSchema fieldSchema)
   at Google.Cloud.BigQuery.V2.BigQueryRow.ConvertRecordArray(JArray array, TableFieldSchema fieldSchema)
   at Google.Cloud.BigQuery.V2.BigQueryRow.ConvertSingleValue(Object rawValue, TableFieldSchema field)
   at Google.Cloud.BigQuery.V2.BigQueryRow.ConvertRecord(JObject record, TableFieldSchema fieldSchema)
   at Google.Cloud.BigQuery.V2.BigQueryRow.ConvertRecordArray(JArray array, TableFieldSchema fieldSchema)
   at Google.Cloud.BigQuery.V2.BigQueryRow.ConvertSingleValue(Object rawValue, TableFieldSchema field)
   at RoutesFeedback.BigQuery.BigQueryService.<GetResultsFromBQ>d__4.MoveNext() in C:\Repos\Routes.Feedback\src\RoutesFeedback.BigQuery\BigQueryService.cs:line 48}
```

Sample code: 
```
BigQueryCommand queryCommand = new BigQueryCommand(
	$@"SELECT * FROM {table}");

BigQueryResults queryResults = await _client
	.ExecuteQuery(queryCommand)
	.PollUntilCompletedAsync();
	
List<BigQueryRow> rows = queryResults
	.GetRows()
	.ToList();

var results = new List<Result>();
foreach (var row in rows)
{
	// System.InvalidCastException: 
	// Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'System.String'
	var routes = row["Routes"]; 

	results.Add(new Result()
	{
		Id = (string)row["Id"],
		LogTime = (DateTime)row["LogTime"],
		RegionId = (string)row["RegionId"],
		Routes = (List<Route>)routes
	});
}
```

P.S. I can send a private message with example row (BigQuery preview) that we need to parse.

**Comment by jskeet** [comment]
If you could create a minimal schema that could demonstrate it, that would be very helpful. Thanks so much for filing the bug :)

**Comment by mantas-paziura** [comment]
I've sent a sample data row to your email. :) P.S. I hope this does not cause any inconveniences.

**Comment by jskeet** [comment]
Hmm. I've tried a repeated string within a record, and a single string within a repeated record. Both work fine so far :(

**Comment by jskeet** [comment]
Hooray - have reproduced now:

```csharp
var client = BigQueryClient.Create(_fixture.ProjectId);
var row = client.ExecuteQuery("SELECT STRUCT<x string>(NULL) AS s").GetRows().Single();
var s = (Dictionary <string, object>) row["s"];
Assert.Null(s["x"]);
```

Fixing now...
