### ISSUE TITLE
Upload fails when using service credentials.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#68]
Here's my code:

```
        public async Task<String> UploadImage(HttpPostedFileBase image, long id)
        {
            var imageAcl = ObjectsResource
                .InsertMediaUpload.PredefinedAclEnum.PublicRead;

            var imageObject = await _storageClient.UploadObjectAsync(
                bucket: _bucketName,
                objectName: id.ToString(),
                contentType: image.ContentType,
                source: image.InputStream,
                options: new UploadObjectOptions { PredefinedAcl = imageAcl }
            );

            return imageObject.MediaLink;
        }
```

When I run it after `gcloud auth login`, it works without error.  When I `gcloud auth revoke,` and then set GOOGLE_APPLICATION_CREDENTIALS, it fails with this error:

<hr>

Value cannot be null.
Parameter name: baseUri

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentNullException: Value cannot be null.
Parameter name: baseUri

Source Error: 

Line 41:                 .InsertMediaUpload.PredefinedAclEnum.PublicRead;
Line 42: 
Line 43:             var imageObject = await _storageClient.UploadObjectAsync(
Line 44:                 bucket: _bucketName,
Line 45:                 objectName: id.ToString(),

Source File: C:\Users\Jeffrey Rennie\gitrepos\getting-started-dotnet\aspnet\3-binary-data\Services\ImageUploader.cs    Line: 43 

<hr>

The exact same credentials work fine with datastore.

**Comment by jskeet** [comment]
Gosh, that's a surprise. I'd hope that at least #58 would do the right thing.

Okay, will look into it ASAP.

**Comment by SurferJeffAtGoogle** [comment]
I'm using 0.1.0-alpha-1.

**Comment by jskeet** [comment]
Hmm. I'm failing to reproduce this at the moment. Do you have the complete stack trace? The top of the stack trace shouldn't be the line that's shown, as that doesn't have a `baseUri` parameter. I assume something is going wrong in the storage `Object` that we're constructing, but it's very hard to tell without a full stack trace :(

**Comment by SurferJeffAtGoogle** [comment]
```
[ArgumentNullException: Value cannot be null.
Parameter name: baseUri]
   Google.Apis.Storage.v1.ClientWrapper.<UploadObjectAsync>d__41.MoveNext() +955
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +137
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +63
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +25
   GoogleCloudSamples.Services.<UploadImage>d__3.MoveNext() in C:\Users\Jeffrey Rennie\gitrepos\getting-started-dotnet\aspnet\3-binary-data\Services\ImageUploader.cs:43
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +137
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +63
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +25
   GoogleCloudSamples.Controllers.<Create>d__7.MoveNext() in C:\Users\Jeffrey Rennie\gitrepos\getting-started-dotnet\aspnet\3-binary-data\Controllers\BooksController.cs:83
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +137
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +63
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +22
   System.Threading.Tasks.TaskHelpersExtensions.ThrowIfFaulted(Task task) +42
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +73
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +37
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +27
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +68
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +69
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +230
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +27
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +27
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +68
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +42
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +124
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +27
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +27
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +48
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +21
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +32
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +26
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +40
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +21
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +24
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +27
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +48
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +21
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +29
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +23
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +129
```

**Comment by jskeet** [comment]
Thanks for that. Async always makes for nasty stack traces, but I'll try to work out what it really means. (In particular, the +955 should help.)

**Comment by jskeet** [comment]
Amidst the multitude of auth issues we've been dealing with recently, is this one now understood and fixed?

**Comment by SurferJeffAtGoogle** [comment]
I haven't seen it recently.  I think the new nuget packages posted to the public myget feed fixed it.

**Comment by jskeet** [comment]
I'm seeing this on Bigquery now (in my experimental client wrapper). When I've got to the bottom of why it's happening, I may be in a better position to understand whether it's still an issue for Storage.

**Comment by SurferJeffAtGoogle** [comment]
I'm seeing this again.

In order to reproduce this error:
1. Run a Google Compute Engine Instance in project A.  Run gcloud auth list to confirm you have default credentials.
2. Create a separate Google Cloud Platform project B, and download a service account B.json. file to the compute engine instance A.
3. In GCE instance A, set the environment variable GOOGLE_APPLICATION_CREDENTIALS to point to the downloaded .json credentials.  Configure everything else in your project to use project B.
4. Run your project on instance A.

**Comment by jskeet** [comment]
So this is trying to use project B credentials from an instance in project A? While I would generally expect that to work, I don't know for sure whether it's a supported scenario. Note that after our next support libraries release, the error message will be a lot clearer.

**Comment by SurferJeffAtGoogle** [comment]
This scenario is very useful for our automated tests running on Jenkins.
The test runner runs as one GCP project, but the test themselves run as a
different GCP project.

**Comment by jskeet** [comment]
Sure, that makes perfect sense in terms of a use case :)

**Comment by jskeet** [comment]
We should have much better error reporting on this now - a while ago we fixed the problem of it just throwing an ArgumentNullException. Jeffrey, are you in a position to easily try this again and post a new stack trace? (I suspect you have the setup in place rather better than I do.)

**Comment by SurferJeffAtGoogle** [comment]
Latest stack trace with `<package id="Google.Storage.V1" version="0.1.0-CI00063" targetFramework="net45" />`

```
Exception in GoogleCloudSamples.Controllers.BooksController:

Value cannot be null.
Parameter name: baseUri

Stack Trace:
   at Google.Storage.V1.StorageClientImpl.<UploadObjectAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoogleCloudSamples.Services.ImageUploader.<UploadImage>d__3.MoveNext() in C:\Users\root\workspace\getting-started-dotnet\aspnet\3-binary-data\Services\ImageUploader.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoogleCloudSamples.Controllers.BooksController.<Edit>d__10.MoveNext() in C:\Users\root\workspace\getting-started-dotnet\aspnet\3-binary-data\Controllers\BooksController.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
```

**Comment by jskeet** [comment]
That's an ancient version of the package. Can you try with beta01?

**Comment by jskeet** [comment]
Or now with beta02? Quite a few things have changed both server and client-side... I have high hopes of this working now.

**Comment by SurferJeffAtGoogle** [comment]
Works with beta02.
