### ISSUE TITLE
RequestStream.WriteAsync() never completes if the speech API has not been enabled.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#723]
This code never completes if the API has not been enabled.
```
var speech = SpeechClient.Create();
            var streamingCall = speech.GrpcClient.StreamingRecognize();
            // Write the initial request with the config.
            await streamingCall.RequestStream.WriteAsync(
```

Non-streaming functions correctly throw an exception:
```
var speech = SpeechClient.Create();
            var response = speech.SyncRecognize(new RecognitionConfig()
            {
                Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                SampleRate = 16000,
            }, RecognitionAudio.FromFile(filePath));
```
```
Test Name:	GoogleCloudSamples.RecognizeTest.TestSync
Test FullName:	GoogleCloudSamples.RecognizeTest.TestSync
Test Source:	C:\Users\root\workspace\dotnet-docs-samples\speech\api\SpeechTest\SpeechTest.cs : line 48
Test Outcome:	Failed
Test Duration:	0:00:04.632

Result1 Name:	GoogleCloudSamples.RecognizeTest.TestSync
Result1 Outcome:	Failed
Result1 Duration:	0:00:02.757
Result1 StackTrace:	
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.Speech.V1Beta1.Speech.SpeechClient.SyncRecognize(SyncRecognizeRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.<>c__DisplayClass6_0.<Sync>b__0(CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.Call[T](TRequest request, CallSettings perCallCallSettings, Func`2 fn)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Cloud.Speech.V1Beta1.SpeechClientImpl.SyncRecognize(SyncRecognizeRequest request, CallSettings callSettings)
   at Google.Cloud.Speech.V1Beta1.SpeechClient.SyncRecognize(RecognitionConfig config, RecognitionAudio audio, CallSettings callSettings)
   at GoogleCloudSamples.Recognize.SyncRecognize(String filePath) in C:\Users\root\workspace\dotnet-docs-samples\speech\api\Recognize\Recognize.cs:line 58
   at GoogleCloudSamples.Recognize.<>c.<Main>b__4_0(SyncOptions opts) in C:\Users\root\workspace\dotnet-docs-samples\speech\api\Recognize\Recognize.cs:line 238
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 notParsedFunc)
   at GoogleCloudSamples.Recognize.Main(String[] args) in C:\Users\root\workspace\dotnet-docs-samples\speech\api\Recognize\Recognize.cs:line 234
   at GoogleCloudSamples.CommandLineRunner.Run(String[] arguments) in C:\Users\root\workspace\dotnet-docs-samples\testutil\TestUtil.cs:line 109
   at GoogleCloudSamples.RecognizeTest.TestSync() in C:\Users\root\workspace\dotnet-docs-samples\speech\api\SpeechTest\SpeechTest.cs:line 49
Result1 Message:	Grpc.Core.RpcException : Status(StatusCode=PermissionDenied, Detail="Google Cloud Speech API has not been used in project getting-started-dotnet before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/speech.googleapis.com/overview?project=getting-started-dotnet then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.")

Result2 Name:	GoogleCloudSamples.RecognizeTest.TestSync
Result2 Outcome:	Failed
Result2 Duration:	0:00:01.875
Result2 StackTrace:	
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.Speech.V1Beta1.Speech.SpeechClient.SyncRecognize(SyncRecognizeRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.<>c__DisplayClass6_0.<Sync>b__0(CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.Call[T](TRequest request, CallSettings perCallCallSettings, Func`2 fn)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Cloud.Speech.V1Beta1.SpeechClientImpl.SyncRecognize(SyncRecognizeRequest request, CallSettings callSettings)
   at Google.Cloud.Speech.V1Beta1.SpeechClient.SyncRecognize(RecognitionConfig config, RecognitionAudio audio, CallSettings callSettings)
   at GoogleCloudSamples.Recognize.SyncRecognize(String filePath) in C:\Users\root\workspace\dotnet-docs-samples\speech\api\Recognize\Recognize.cs:line 58
   at GoogleCloudSamples.Recognize.<>c.<Main>b__4_0(SyncOptions opts) in C:\Users\root\workspace\dotnet-docs-samples\speech\api\Recognize\Recognize.cs:line 238
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 notParsedFunc)
   at GoogleCloudSamples.Recognize.Main(String[] args) in C:\Users\root\workspace\dotnet-docs-samples\speech\api\Recognize\Recognize.cs:line 234
   at GoogleCloudSamples.CommandLineRunner.Run(String[] arguments) in C:\Users\root\workspace\dotnet-docs-samples\testutil\TestUtil.cs:line 109
   at GoogleCloudSamples.RecognizeTest.TestSync() in C:\Users\root\workspace\dotnet-docs-samples\speech\api\SpeechTest\SpeechTest.cs:line 49
Result2 Message:	Grpc.Core.RpcException : Status(StatusCode=PermissionDenied, Detail="Google Cloud Speech API has not been used in project getting-started-dotnet before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/speech.googleapis.com/overview?project=getting-started-dotnet then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.")

```

**Comment by SurferJeffAtGoogle** [comment]
Correction: it never completes if run on a Compute Engine VM.

**Comment by jskeet** [comment]
@jtattermusch: Do you know anything about this? Like Jeffrey, I'd expect this to fail.

**Comment by jtattermusch** [comment]
Perhaps it has something to do with https://github.com/grpc/grpc/issues/9249?

Please try setting the environment variable `GRPC_VERBOSITY=DEBUG` and enabling logging in gRPC C#
`GrpcEnvironment.SetLogger(new Grpc.Core.Logging.ConsoleLogger());`, then we might know more.

**Comment by jskeet** [comment]
Jeff, any more information on this? Are you still able to reproduce?

**Comment by SurferJeffAtGoogle** [comment]
I haven't had time to retry.

**Comment by jskeet** [comment]
Just tried this, and it failed appropriately.

(It fails when calling MoveNext on the response stream, rather than on the request, but I think that's okay.)
