### ISSUE TITLE
UrlSigner resumable uploads fail on .NET Core

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#824]
Our integration test passes in net451, but fails in .NET Core. I haven't got to the bottom of why yet, but it looks like it was broken in 1.0.0-beta07, so it's not very recent. It's possible that it's a problem with Google.Apis instead, but it's hard to tell without digging in further.

I'll have a look when I can, but Mike may well be better placed to understand what's going on.

**Comment by jskeet** [comment]
Full stack trace, not that it's terribly enlightening:

```text
    Google.Cloud.Storage.V1.IntegrationTests.UrlSignerTest.ResumableUploadResumeTest [FAIL]
      Google.GoogleApiException : Not Found
      Stack Trace:
        c:\Users\skeet\Test\Projects\google-cloud-dotnet\apis\Google.Cloud.Storage.V1\Google.Cloud.Storage.V1\StorageClientImpl.DownloadObject.cs(144,0): at Google.Cloud.Storage.V1.StorageClientImpl.<DownloadObjectAsyncImpl>d__47.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        c:\Users\skeet\Test\Projects\google-cloud-dotnet\apis\Google.Cloud.Storage.V1\Google.Cloud.Storage.V1.IntegrationTests\UrlSignerTest.cs(594,0): at Google.Cloud.Storage.V1.IntegrationTests.UrlSignerTest.<>c__DisplayClass31_0.<<ResumableUploadResumeTest_InitDelayTest>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        c:\Users\skeet\Test\Projects\google-cloud-dotnet\apis\Google.Cloud.Storage.V1\Google.Cloud.Storage.V1.IntegrationTests\StorageFixture.cs(279,0): at Google.Cloud.Storage.V1.IntegrationTests.StorageFixture.DelayTestInfo.<StartTest>d__15.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        c:\Users\skeet\Test\Projects\google-cloud-dotnet\apis\Google.Cloud.Storage.V1\Google.Cloud.Storage.V1.IntegrationTests\StorageFixture.cs(294,0): at Google.Cloud.Storage.V1.IntegrationTests.StorageFixture.DelayTestInfo.OnTestFinalizing()
        c:\Users\skeet\Test\Projects\google-cloud-dotnet\apis\Google.Cloud.Storage.V1\Google.Cloud.Storage.V1.IntegrationTests\StorageFixture.cs(188,0): at Google.Cloud.Storage.V1.IntegrationTests.StorageFixture.<FinishDelayTest>d__57.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        c:\Users\skeet\Test\Projects\google-cloud-dotnet\apis\Google.Cloud.Storage.V1\Google.Cloud.Storage.V1.IntegrationTests\UrlSignerTest.cs(575,0): at Google.Cloud.Storage.V1.IntegrationTests.UrlSignerTest.<ResumableUploadResumeTest>d__30.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

The "Not Found" is due to the upload failing. That can be seen with `progress.Exception`, but I don't have a stack trace to hand for it - and it wasn't hugely enlightening beyond saying that a redirect had failed.

**Comment by evildour** [comment]
I cannot reproduce, so maybe it was a temporary issue with Storage as you suggested offline. However, the test just ignores the result of the upload, so I'm going to change things so if this happened again in the future, we can hopefully get some better info.

**Comment by jskeet** [comment]
Will have another test of this on Monday and close it if everything passes.

**Comment by jskeet** [comment]
Annoyingly, it's still failing for me, still only under .NET Core.

So this works:

> dotnet test -f net451 Google.Cloud.Storage.V1.IntegrationTests -method Google.Cloud.Storage.V1.IntegrationTests.UrlSi
gnerTest.ResumableUploadResumeTest

But this fails:

> dotnet test -f netcoreapp1.0 Google.Cloud.Storage.V1.IntegrationTests -method Google.Cloud.Storage.V1.IntegrationTests.UrlSi
gnerTest.ResumableUploadResumeTest

Mike, could you check that that exact command passes for you?

**Comment by evildour** [comment]
I ran each command twice and all four runs pass for me. Are you getting any additional info from the recent changes to the tests?

**Comment by jskeet** [comment]
Sorry, yes - I thought I'd put the extra stack trace in before, but apparently not. Here it is:

```text
    Google.Cloud.Storage.V1.IntegrationTests.UrlSignerTest.ResumableUploadResumeTest [FAIL]
      Assert.Null() Failure
      Expected: (null)
      Actual:   System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The HTTP redirect request failed
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
         --- End of inner exception stack trace ---
         at Google.Apis.Http.ConfigurableMessageHandler.<SendAsync>d__43.MoveNext() in C:\Apiary\v1.21\google-api-dotnet-client\Src\Support\GoogleApis.Core\Apis\Http\ConfigurableMessageHandler.cs:line 346
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Google.Apis.Upload.ResumableUpload.<ResumeAsync>d__72.MoveNext() in C:\Apiary\v1.21\google-api-dotnet-client\Src\Support\GoogleApis\Apis\[Media]\Upload\ResumableUpload.cs:line 541
      Stack Trace:
        c:\Users\skeet\Test\Projects\google-cloud-dotnet\apis\Google.Cloud.Storage.V1\Google.Cloud.Storage.V1.IntegrationTests\UrlSignerTest.cs(593,0): at Google.Cloud.Storage.V1.IntegrationTests.UrlSignerTest.<>c__DisplayClass31_0.<<ResumableUploadResumeTest_InitDelayTest>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        c:\Users\skeet\Test\Projects\google-cloud-dotnet\apis\Google.Cloud.Storage.V1\Google.Cloud.Storage.V1.IntegrationTests\StorageFixture.cs(279,0): at Google.Cloud.Storage.V1.IntegrationTests.StorageFixture.DelayTestInfo.<StartTest>d__15.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        c:\Users\skeet\Test\Projects\google-cloud-dotnet\apis\Google.Cloud.Storage.V1\Google.Cloud.Storage.V1.IntegrationTests\StorageFixture.cs(294,0): at Google.Cloud.Storage.V1.IntegrationTests.StorageFixture.DelayTestInfo.OnTestFinalizing()
        c:\Users\skeet\Test\Projects\google-cloud-dotnet\apis\Google.Cloud.Storage.V1\Google.Cloud.Storage.V1.IntegrationTests\StorageFixture.cs(188,0): at Google.Cloud.Storage.V1.IntegrationTests.StorageFixture.<FinishDelayTest>d__57.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        c:\Users\skeet\Test\Projects\google-cloud-dotnet\apis\Google.Cloud.Storage.V1\Google.Cloud.Storage.V1.IntegrationTests\UrlSignerTest.cs(575,0): at Google.Cloud.Storage.V1.IntegrationTests.UrlSignerTest.<ResumableUploadResumeTest>d__30.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

I've included absolutely everything just in case, although I only expect the first few lines to be relevant.

**Comment by jskeet** [comment]
(Next stop is probably to run Fiddler and see if I can get the details at an HTTP level...)

**Comment by evildour** [comment]
Hmm, it is a bit odd about the line number being on an if statement in the ConfigurableMessageHandler.cs. I checked history and this file hasn't changed recently where there used to be something there that might throw. Can you check the loaded modules to make sure the latest Google.Apis.Core is getting loaded, and not some local copy that may have been edited or something? The path shows something not in the nuget packages folder, so I'm wondering if maybe something else is getting loaded.

**Comment by jskeet** [comment]
Will see what I can do. Debugging on Core isn't always as simple as it might be, but I'll see where I get...

**Comment by jskeet** [comment]
No joy - I blew away my nuget cache and restored, and it's definitely getting it from there.

With Fiddler I can see it making 3 PUT requests to https://storage.googleapis.com/[...] each receiving a 308 response. It never specifies a Content-Range header, but has Content-Length 0.

In the working case, there's a PUT request with Content-Length 0, Content-Range bytes */12, then another one of Content-Length 12, Content-Range bytes 0-11/12

Very odd.

**Comment by evildour** [comment]
That's odd. Based on [this line](https://github.com/evildour/google-api-dotnet-client/blob/master/Src/Support/GoogleApis/Apis/%5BMedia%5D/Upload/ResumableUpload.cs#L533), if `ResumeAsync` is called on a `ResumableUpload` instance and a non-null URI is specified, the Content-Range header should always be set. Perhaps `SignedUrlResumableUpload.InitiateSessionAsync` is producing a null session URI (can you add a temporary check to the test for this). If not, something is either stripping it out or this code is not being used to create the request somehow.

As far as loading the right assembly, my concern was that in the stack trace, the odd line number is coming from a file in this path:
C:\Apiary\v1.21\google-api-dotnet-client\...
Which does not seem to be in the nuget cache.

**Comment by jskeet** [comment]
Just reproduced this on another machine, so it's unlikely to be anything to do with my nuget cache. (And C:\Apiary\v1.21\google-api-dotnet-client should be fine for the support libraries, although the line number for ConfigurableHttpClient is strange.)

Delving into this a bit more...

**Comment by jskeet** [comment]
Current hypothesis: the netstandard-1.3 HttpClient drops the Content-Range header if the content length is 0. Going to investigate that outside this environment...

**Comment by jskeet** [comment]
Ignore the part about the Content-Range header. It *is* there - I must have been looking at the response.

In the working version, there are two requests to the same URL: one with no data, then a second one with data. The first gets a 308 response, the second gets a 200 response.

In the broken version, the first request and response is the same, but the second request *doesn't* contain the data - it's just a repeat of the first.

What I haven't worked out yet is whether this only affects signed URLs.

**Comment by jskeet** [comment]
Getting closer... if I specify a `ResumableUploadOptions` with an `HttpClient` created by a `StorageClient`, it works. So it's something about the `ConfigurableHttpClient` that it's using that differs...

**Comment by jskeet** [comment]
Got it!

This is the bug, in ResumableUpload:

```csharp
HttpClient = options?.ConfigurableHttpClient ?? new ConfigurableHttpClient(new ConfigurableMessageHandler(new HttpClientHandler()));
```

That doesn't use `HttpClientFactory`  - which sets up the inner `HttpClientHandler` to *not* automatically follow redirects. So basically the .NET Core implementation of `HttpClientHandler` automatically tries to follow 308 as a redirect (despite there being no location header) rather than letting `ConfigurableHttpClientHandler` do it. I'm not sure whether the desktop framework implementation simply handles redirects differently. Will file a bug in google-api-dotnet-client...

**Comment by evildour** [comment]
Thanks for figuring this out. I introduced this and was not aware of `HttpClientFactory`. I'm still not sure why it worked fine for me though.

**Comment by evildour** [comment]
Oops, looks like I was aware of it when I created the metadata client library and somehow I forgot about it.

**Comment by jskeet** [comment]
No problem - I'm just glad we've mostly got to the bottom of it. I wonder whether we're using very slightly different versions of .NET Core which behave differently around redirects...

**Comment by evildour** [comment]
Looks like I have 1.0.1, build `cee57bf6c981237d80aa1631cfe83cb9ba329f12`.

**Comment by jskeet** [comment]
I have lots of builds on the machine, but I get lost when trying to work out exactly which version of which library gets loaded :)
