### ISSUE TITLE
LoggingV2: Grpc.Core.RpcException on GAE

### ISSUE THREAD

**Issue by Jonathan34** [GoogleCloudPlatform/google-cloud-dotnet#950]
using .net core 1.1, and package <PackageReference Include="Google.Cloud.Diagnostics.AspNetCore" Version="1.0.0-alpha07" />

```
Mac:UDL-API$ dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 `Version:`            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

I use the logging API to log entries to stackdriver. Seems to work fine but from time to time i get this exception in GAE:
```
Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="{"created":"@1490882606.897263341","description":"Secure read failed","file":"src/core/lib/security/transport/secure_endpoint.c","file_line":157,"grpc_status":14,"referenced_errors":[{"created":"@1490882606.897219764","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235}]}")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.Logging.V2.LoggingServiceV2.LoggingServiceV2Client.WriteLogEntries(WriteLogEntriesRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Cloud.Diagnostics.Common.TimedBufferingConsumer`1.FlushWithSemaphoreHeld()
   at Google.Cloud.Diagnostics.Common.FlushableConsumerBase`1.Flush()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```
and then the application restarts.

or even
```
Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.Logging.V2.LoggingServiceV2.LoggingServiceV2Client.WriteLogEntries(WriteLogEntriesRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Cloud.Diagnostics.Common.TimedBufferingConsumer`1.FlushWithSemaphoreHeld()
   at Google.Cloud.Diagnostics.Common.FlushableConsumerBase`1.Flush()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

![image](https://cloud.githubusercontent.com/assets/3976137/24512529/6bfdd99e-1534-11e7-845b-e801cb541682.png)

**Comment by iantalarico** [comment]
We have Issue #842 to generally handle failure in the libraries. I think we will make this configurable eventually.  Do you have input or requests on this front?

Are you pinned to a version of "Google.Cloud.Diagnostics.Common"?

@jskeet may have more general suggestions on DeadlineExceeded.

**Comment by jskeet** [comment]
When you say "in GAE" do you mean your application is running in GAE Flexible Environment?

@chrisdunelm Could you check the config here? Given that it's non-idempotent, I think this will fail if the first call fails with deadline exceeded, which it will do after 2 seconds.

**Comment by jskeet** [comment]
See also #842 and #846. Could you tell us which version of the Google libraries you're currently using?

**Comment by Jonathan34** [comment]
Yes GAE Flexible as we are using net core. I can eventually privately share the url to the google project to someone in google if it helps .
I only use the version `1.0.0-alpha07` of the `Google.Cloud.Diagnostics.AspNetCore package`, nothing else.

**Comment by iantalarico** [comment]
@Jonathan34 no need to share the project at this point.  This is a semi known issue as mentioned in #842.

This should not be failure should not be restarting or crashing yours instances.  Can you confirm that this is happening?

**Comment by chrisdunelm** [comment]
The config file is [logging_gapic.yaml](https://github.com/googleapis/googleapis/blob/master/google/logging/v2/logging_gapic.yaml). `WriteLogEntries` is [non-idempotent](https://github.com/googleapis/googleapis/blob/master/google/logging/v2/logging_gapic.yaml#L350), so it only retries on [UNAVAILABLE](https://github.com/googleapis/googleapis/blob/master/google/logging/v2/logging_gapic.yaml#L306). It uses the `default` timeout params, which means it has a [2s timeout](https://github.com/googleapis/googleapis/blob/master/google/logging/v2/logging_gapic.yaml#L312).

**Comment by Jonathan34** [comment]
@iantalarico i have to admit it s hard to be sure this exception kills my asp.net core service.
I have extracted a part of a log here: https://gist.github.com/Jonathan34/1394a6a904b7be4896c195d875b2fee1

**Comment by iantalarico** [comment]
@Jonathan34 okay I'll look into the logs a little.  We do a pretty general catch of all RPC exceptions that would kill that app that are running in our timer, so hopefully this isn't causing the issue but I dig in.

**Comment by iantalarico** [comment]
I took a look through those logs and I'm not sure what is going on either.  It's fairly confusing. 
jskeet is pushing a new version of the diagnostic bits soon.  The fix I had talked about earlier may not have made it into the last release so this new version make fix it.

**Comment by jskeet** [comment]
The new bits are out, so that should stop the crash - but it's possible that we should extend the timeout.

@Jonathan34: Do you have a sense of how many log entries you're writing? It would help us to reproduce this separately.

**Comment by Jonathan34** [comment]
I do not see this error anymore with the upgrade. i guess it can be closed. i will reopen it if i see it again!

**Comment by jskeet** [comment]
SGTM.
