### ISSUE TITLE
Exception when I call TranslateText(...,TranslationModel.NeuralMachineTranslation)

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#961]
```
Unhandled Exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Invalid JSON payload received. Unknown name "model": Cannot bind 'nmt'. Field 'model' could not be found in request mess
age. [400]
Errors [
        Message[Invalid JSON payload received. Unknown name "model": Cannot bind 'nmt'. Field 'model' could not be found
 in request message.] Location[ - ] Reason[badRequest] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at Google.Cloud.Translation.V2.TranslationClientImpl.TranslateText(String text, String targetLanguage, String sourceL
anguage, Nullable`1 model)
   at GoogleCloudSamples.Translator.TranslateWithModel(TranslateArgs args)
   at GoogleCloudSamples.Translator.<>c.<Main>b__0_0(TranslateArgs targs)
   at GoogleCloudSamples.Translator.Main(String[] args)
```

**Comment by jskeet** [comment]
Do you have a premium account? I believe this is the error message returned when trying to use NMT from a non-premium account. (It could certainly be clearer.) Will ping you internally...

**Comment by SurferJeffAtGoogle** [comment]
I probably do not have a premium account.

**Comment by SurferJeffAtGoogle** [comment]
I do not have a premium account.

**Comment by jskeet** [comment]
Closing as obsolete, as the model parameter is now available to all.
